import type { Contact, TargetLead, PortfolioCompany } from "./types";

export const sampleContacts: Contact[] = [
  {
    id: "1",
    name: "Sarah Chen",
    title: "VP of Growth",
    company: "Glossier",
    email: "s.chen@glossier.com",
    phone: "+1 (212) 555-0142",
    address: "233 Spring St, New York, NY 10013",
    prime: "Michael Torres",
    sector: "Beauty & Personal Care",
    areasOfInterest: ["DTC Growth Strategy", "Brand Building", "Customer Acquisition"],
    temperature: "Hot",
    portCoIntros: ["Allbirds", "Warby Parker"],
    eventsAttended: ["DTC Summit 2024", "Beauty Connect NYC"],
    eventsInvited: ["DTC Summit 2024", "Beauty Connect NYC", "Future of Retail 2024"],
    interactions: [
      { id: "i1", date: "2024-03-15", type: "meeting", summary: "Strategy session on DTC growth" },
      { id: "i2", date: "2024-03-08", type: "email", summary: "Shared portfolio company deck" },
      { id: "i3", date: "2024-02-20", type: "intro", summary: "Intro to Allbirds CEO" },
      { id: "i16", date: "2024-03-18", type: "follow-up", summary: "Schedule follow-up re: partnership", isFollowUp: true, followUpComplete: false },
    ],
    lastContact: "2024-03-15",
    followUpPending: true,
    location: "New York, NY",
  },
  {
    id: "2",
    name: "James Rodriguez",
    title: "Chief Revenue Officer",
    company: "Athletic Greens",
    email: "j.rodriguez@athleticgreens.com",
    phone: "+1 (512) 555-0198",
    address: "1100 Congress Ave, Austin, TX 78701",
    prime: "Lisa Park",
    sector: "Health & Wellness",
    areasOfInterest: ["Revenue Optimization", "Subscription Models"],
    temperature: "Warm",
    portCoIntros: ["Peloton"],
    eventsAttended: ["Wellness Innovation Forum"],
    eventsInvited: ["Wellness Innovation Forum", "Health Tech Conference"],
    interactions: [
      { id: "i4", date: "2024-03-10", type: "call", summary: "Discussed market expansion" },
      { id: "i5", date: "2024-02-28", type: "event", summary: "Met at Wellness Innovation Forum" },
    ],
    lastContact: "2024-03-10",
    followUpPending: false,
    location: "Austin, TX",
  },
  {
    id: "3",
    name: "Emily Watson",
    title: "Director of Strategy",
    company: "Casper",
    email: "e.watson@casper.com",
    phone: "+1 (415) 555-0267",
    address: "175 Greenwich St, San Francisco, CA 94111",
    prime: "David Kim",
    sector: "Home & Living",
    areasOfInterest: ["Market Expansion"],
    temperature: "Cold",
    portCoIntros: [],
    eventsAttended: ["Retail Innovation Summit"],
    eventsInvited: ["Retail Innovation Summit", "DTC Summit 2024"],
    interactions: [
      { id: "i6", date: "2024-01-15", type: "email", summary: "Initial outreach" },
      { id: "i17", date: "2024-02-01", type: "follow-up", summary: "Follow up on outreach email", isFollowUp: true, followUpComplete: true },
    ],
    lastContact: "2024-01-15",
    followUpPending: true,
    location: "San Francisco, CA",
  },
  {
    id: "4",
    name: "Alex Patel",
    title: "Head of Partnerships",
    company: "Hims & Hers",
    email: "a.patel@forhims.com",
    phone: "+1 (415) 555-0334",
    address: "2269 Chestnut St, San Francisco, CA 94123",
    prime: "Michael Torres",
    sector: "Health & Wellness",
    areasOfInterest: ["Strategic Partnerships", "Telehealth", "Distribution"],
    temperature: "Hot",
    portCoIntros: ["Roman", "Nurx"],
    eventsAttended: ["DTC Summit 2024", "Health Tech Conference"],
    eventsInvited: ["DTC Summit 2024", "Health Tech Conference"],
    interactions: [
      { id: "i7", date: "2024-03-14", type: "meeting", summary: "Portfolio synergy review" },
      { id: "i8", date: "2024-03-01", type: "intro", summary: "Connected with Roman leadership" },
      { id: "i9", date: "2024-02-15", type: "call", summary: "Quarterly check-in" },
      { id: "i18", date: "2024-03-16", type: "follow-up", summary: "Send synergy analysis doc", isFollowUp: true, followUpComplete: false },
    ],
    lastContact: "2024-03-14",
    followUpPending: true,
    location: "San Francisco, CA",
  },
  {
    id: "5",
    name: "Mia Thompson",
    title: "Brand Director",
    company: "Away",
    email: "m.thompson@awaytravel.com",
    phone: "+1 (212) 555-0478",
    address: "595 Broadway, New York, NY 10012",
    prime: "Lisa Park",
    sector: "Travel & Lifestyle",
    areasOfInterest: ["Brand Strategy"],
    temperature: "Warm",
    portCoIntros: ["Rimowa"],
    eventsAttended: ["Luxury Retail Summit"],
    eventsInvited: ["Luxury Retail Summit"],
    interactions: [
      { id: "i10", date: "2024-03-05", type: "email", summary: "Shared travel sector report" },
    ],
    lastContact: "2024-03-05",
    followUpPending: false,
    location: "New York, NY",
  },
  {
    id: "6",
    name: "Ryan O'Brien",
    title: "General Manager",
    company: "Dollar Shave Club",
    email: "r.obrien@dollarshaveclub.com",
    phone: "+1 (310) 555-0512",
    address: "13335 Maxella Ave, Los Angeles, CA 90292",
    prime: "David Kim",
    sector: "Beauty & Personal Care",
    areasOfInterest: ["Subscription Models"],
    temperature: "Cold",
    portCoIntros: [],
    eventsAttended: [],
    eventsInvited: ["DTC Summit 2024"],
    interactions: [
      { id: "i11", date: "2024-02-01", type: "note", summary: "Added from conference list" },
    ],
    lastContact: "2024-02-01",
    followUpPending: false,
    location: "Los Angeles, CA",
  },
  {
    id: "7",
    name: "Priya Sharma",
    title: "VP of Social Impact",
    company: "Bombas",
    email: "p.sharma@bombas.com",
    phone: "+1 (212) 555-0633",
    address: "45 W 27th St, New York, NY 10001",
    prime: "Michael Torres",
    sector: "Apparel & Fashion",
    areasOfInterest: ["Social Impact & ESG", "Sustainability", "Community Building"],
    temperature: "Hot",
    portCoIntros: ["Everlane", "Allbirds"],
    eventsAttended: ["DTC Summit 2024", "Social Impact Conference"],
    eventsInvited: ["DTC Summit 2024", "Social Impact Conference", "Future of Retail 2024"],
    interactions: [
      { id: "i12", date: "2024-03-12", type: "meeting", summary: "Deep dive on social impact metrics" },
      { id: "i13", date: "2024-03-02", type: "intro", summary: "Intro to Everlane founders" },
      { id: "i19", date: "2024-03-14", type: "note", summary: "Priya mentioned interest in climate-focused portfolio companies" },
      { id: "i20", date: "2024-03-15", type: "follow-up", summary: "Send climate portfolio summary", isFollowUp: true, followUpComplete: false },
    ],
    lastContact: "2024-03-12",
    followUpPending: true,
    location: "New York, NY",
  },
  {
    id: "8",
    name: "Chris Nakamura",
    title: "SVP of Retail Strategy",
    company: "Warby Parker",
    email: "c.nakamura@warbyparker.com",
    phone: "+1 (212) 555-0745",
    address: "161 Avenue of the Americas, New York, NY 10013",
    prime: "Lisa Park",
    sector: "Apparel & Fashion",
    areasOfInterest: ["Retail Innovation"],
    temperature: "Warm",
    portCoIntros: ["Glossier"],
    eventsAttended: ["Retail Innovation Summit", "DTC Summit 2024"],
    eventsInvited: ["Retail Innovation Summit", "DTC Summit 2024"],
    interactions: [
      { id: "i14", date: "2024-03-08", type: "call", summary: "Discussed retail expansion strategy" },
      { id: "i15", date: "2024-02-22", type: "email", summary: "Follow-up on retail trends report" },
    ],
    lastContact: "2024-03-08",
    followUpPending: false,
    location: "New York, NY",
  },
];

export const sectors = [
  "Apparel & Fashion",
  "Beauty & Personal Care",
  "Food & Beverage",
  "Health & Wellness",
  "Home & Living",
  "Travel & Lifestyle",
];

export const primes = ["Michael Torres", "Lisa Park", "David Kim"];

export const portfolioCompanyNames = [
  "Allbirds",
  "Warby Parker",
  "Peloton",
  "Roman",
  "Nurx",
  "Rimowa",
  "Everlane",
  "Glossier",
];

// Keep backward compat
export const portfolioCompanies = portfolioCompanyNames;

export const samplePortfolioCompanies: PortfolioCompany[] = [
  {
    id: "pc1",
    name: "Allbirds",
    sector: "Apparel & Fashion",
    domain: "Supply Chain",
    website: "https://www.allbirds.com",
    linkedinUrl: "https://linkedin.com/company/allbirds",
    location: "San Francisco, CA",
    description: "Sustainable footwear and apparel brand using natural materials like merino wool and eucalyptus fiber.",
    contactName: "Joey Zwillinger",
    contactEmail: "joey@allbirds.com",
    contactPhone: "+1 (415) 555-1001",
    employees: [
      { id: "pe1", name: "Joey Zwillinger", title: "Co-CEO", email: "joey@allbirds.com", linkedinUrl: "https://linkedin.com/in/joeyzwillinger" },
      { id: "pe2", name: "Hana Kajimura", title: "Head of Sustainability", email: "hana@allbirds.com", linkedinUrl: "https://linkedin.com/in/hanakajimura" },
      { id: "pe3", name: "Travis Boatman", title: "VP of Marketing", email: "travis@allbirds.com", linkedinUrl: "https://linkedin.com/in/travisboatman" },
    ],
    events: [
      { id: "ev1", date: "2024-03-10", name: "DTC Summit 2024", type: "conference" },
      { id: "ev2", date: "2024-02-15", name: "Portfolio Dinner Q1", type: "dinner" },
      { id: "ev3", date: "2024-01-20", name: "Sustainability Webinar", type: "webinar" },
    ],
    introductions: [
      { id: "in1", date: "2024-03-15", targetName: "Sarah Chen", targetCompany: "Glossier", introducedBy: "Michael Torres", outcome: "Follow-up meeting scheduled" },
      { id: "in2", date: "2024-02-20", targetName: "Priya Sharma", targetCompany: "Bombas", introducedBy: "Michael Torres", outcome: "Exploring co-marketing" },
      { id: "in3", date: "2024-01-10", targetName: "Jason Lee", targetCompany: "Rothy's", introducedBy: "David Kim", outcome: "Initial call completed" },
    ],
  },
  {
    id: "pc2",
    name: "Warby Parker",
    sector: "Apparel & Fashion",
    domain: "Data",
    website: "https://www.warbyparker.com",
    linkedinUrl: "https://linkedin.com/company/warby-parker",
    location: "New York, NY",
    description: "Direct-to-consumer eyewear company offering designer glasses at affordable prices with a social mission.",
    contactName: "Neil Blumenthal",
    contactEmail: "neil@warbyparker.com",
    contactPhone: "+1 (212) 555-2002",
    employees: [
      { id: "pe4", name: "Neil Blumenthal", title: "Co-CEO", email: "neil@warbyparker.com", linkedinUrl: "https://linkedin.com/in/neilblumenthal" },
      { id: "pe5", name: "Dave Gilboa", title: "Co-CEO", email: "dave@warbyparker.com", linkedinUrl: "https://linkedin.com/in/davegilboa" },
    ],
    events: [
      { id: "ev4", date: "2024-03-10", name: "DTC Summit 2024", type: "conference" },
      { id: "ev5", date: "2024-02-28", name: "Retail Innovation Summit", type: "conference" },
    ],
    introductions: [
      { id: "in4", date: "2024-03-08", targetName: "Chris Nakamura", targetCompany: "Warby Parker", introducedBy: "Lisa Park", outcome: "Partnership discussion ongoing" },
    ],
  },
  {
    id: "pc3",
    name: "Peloton",
    sector: "Health & Wellness",
    domain: "Cloud",
    website: "https://www.onepeloton.com",
    linkedinUrl: "https://linkedin.com/company/peloton-interactive",
    location: "New York, NY",
    description: "Connected fitness platform offering interactive workout classes through hardware and subscription services.",
    contactName: "Barry McCarthy",
    contactEmail: "barry@onepeloton.com",
    contactPhone: "+1 (212) 555-3003",
    employees: [
      { id: "pe6", name: "Barry McCarthy", title: "CEO", email: "barry@onepeloton.com", linkedinUrl: "https://linkedin.com/in/barrymccarthy" },
      { id: "pe7", name: "Liz Coddington", title: "CFO", email: "liz@onepeloton.com", linkedinUrl: "https://linkedin.com/in/lizcoddington" },
      { id: "pe8", name: "Dion Sanders", title: "VP of Partnerships", email: "dion@onepeloton.com", linkedinUrl: "https://linkedin.com/in/dionsanders" },
    ],
    events: [
      { id: "ev6", date: "2024-03-05", name: "Health Tech Conference", type: "conference" },
      { id: "ev7", date: "2024-02-15", name: "Portfolio Dinner Q1", type: "dinner" },
    ],
    introductions: [
      { id: "in5", date: "2024-03-10", targetName: "James Rodriguez", targetCompany: "Athletic Greens", introducedBy: "Lisa Park", outcome: "Intro call held, exploring wellness bundle" },
    ],
  },
  {
    id: "pc4",
    name: "Glossier",
    sector: "Beauty & Personal Care",
    domain: "AI",
    website: "https://www.glossier.com",
    linkedinUrl: "https://linkedin.com/company/glossier",
    location: "New York, NY",
    description: "Beauty brand born from content, building products inspired by real life.",
    contactName: "Kyle Leahy",
    contactEmail: "kyle@glossier.com",
    contactPhone: "+1 (212) 555-4004",
    employees: [
      { id: "pe9", name: "Kyle Leahy", title: "CEO", email: "kyle@glossier.com", linkedinUrl: "https://linkedin.com/in/kyleleahy" },
      { id: "pe10", name: "Marie Suter", title: "CMO", email: "marie@glossier.com", linkedinUrl: "https://linkedin.com/in/mariesuter" },
    ],
    events: [
      { id: "ev8", date: "2024-03-10", name: "Beauty Connect NYC", type: "conference" },
      { id: "ev9", date: "2024-01-25", name: "DTC Founders Dinner", type: "dinner" },
    ],
    introductions: [
      { id: "in6", date: "2024-03-15", targetName: "Sarah Chen", targetCompany: "Glossier", introducedBy: "Michael Torres", outcome: "Strategy session scheduled" },
      { id: "in7", date: "2024-02-05", targetName: "Ryan O'Brien", targetCompany: "Dollar Shave Club", introducedBy: "David Kim", outcome: "Initial outreach — no response yet" },
    ],
  },
  {
    id: "pc5",
    name: "Everlane",
    sector: "Apparel & Fashion",
    domain: "Logistics",
    website: "https://www.everlane.com",
    linkedinUrl: "https://linkedin.com/company/everlane",
    location: "San Francisco, CA",
    description: "Transparent pricing fashion brand focused on ethical factories and radical transparency.",
    contactName: "Andrea O'Donnell",
    contactEmail: "andrea@everlane.com",
    contactPhone: "+1 (415) 555-5005",
    employees: [
      { id: "pe11", name: "Andrea O'Donnell", title: "CEO", email: "andrea@everlane.com", linkedinUrl: "https://linkedin.com/in/andreaodonnell" },
    ],
    events: [
      { id: "ev10", date: "2024-02-15", name: "Portfolio Dinner Q1", type: "dinner" },
    ],
    introductions: [
      { id: "in8", date: "2024-03-02", targetName: "Priya Sharma", targetCompany: "Bombas", introducedBy: "Michael Torres", outcome: "Sustainability collaboration discussed" },
    ],
  },
];

export const sampleTargets: TargetLead[] = [
  {
    id: "t1",
    name: "Lauren Fischer",
    title: "VP of Growth",
    phone: "",
    company: "Fabletics",
    linkedinUrl: "https://linkedin.com/in/laurenfischer",
    email: "l.fischer@fabletics.com",
    location: "Los Angeles, CA",
    sector: "Apparel & Fashion",
    stage: "Researching",
    originSource: "DTC Summit 2024",
    outreach: [
      { id: "o1", date: "2024-03-10", method: "LinkedIn", summary: "Connection request sent" },
    ],
    notes: "Strong DTC background, previously at Adidas",
  },
  {
    id: "t2",
    name: "Derek Huang",
    title: "Director of Partnerships",
    phone: "",
    company: "Liquid Death",
    linkedinUrl: "https://linkedin.com/in/derekhuang",
    email: "d.huang@liquiddeath.com",
    location: "Los Angeles, CA",
    sector: "Food & Beverage",
    stage: "Prospecting",
    originSource: "Referral — Lisa Park",
    outreach: [],
    notes: "",
  },
  {
    id: "t3",
    name: "Nina Patel",
    title: "Head of Business Development",
    phone: "",
    company: "Oura",
    linkedinUrl: "https://linkedin.com/in/ninapatel",
    email: "n.patel@ouraring.com",
    location: "San Francisco, CA",
    sector: "Health & Wellness",
    stage: "Outreach Sent",
    originSource: "Health Tech Conference",
    outreach: [
      { id: "o2", date: "2024-03-05", method: "Email", summary: "Intro email sent" },
      { id: "o3", date: "2024-03-12", method: "LinkedIn", summary: "Follow-up message" },
    ],
    notes: "Interested in wearable health data partnerships",
  },
  {
    id: "t4",
    name: "Marcus Cole",
    title: "Chief Revenue Officer",
    phone: "",
    company: "Vuori",
    linkedinUrl: "https://linkedin.com/in/marcuscole",
    email: "m.cole@vuori.com",
    location: "Carlsbad, CA",
    sector: "Apparel & Fashion",
    stage: "Ready to Promote",
    originSource: "DTC Summit 2024",
    outreach: [
      { id: "o4", date: "2024-02-20", method: "Email", summary: "Initial outreach" },
      { id: "o5", date: "2024-03-01", method: "Call", summary: "15-min intro call" },
      { id: "o6", date: "2024-03-14", method: "Meeting", summary: "Strategy discussion — ready to move to CRM" },
    ],
    notes: "Great fit for portfolio synergy with Allbirds",
  },
  {
    id: "t5",
    name: "Sophie Martinez",
    title: "",
    phone: "",
    company: "Ritual",
    linkedinUrl: "https://linkedin.com/in/sophiemartinez",
    email: "s.martinez@ritual.com",
    location: "New York, NY",
    sector: "Health & Wellness",
    stage: "Prospecting",
    originSource: "Conference list import",
    outreach: [],
    notes: "",
  },
  {
    id: "t6",
    name: "Jason Lee",
    title: "Sustainability Lead",
    phone: "",
    company: "Rothy's",
    linkedinUrl: "https://linkedin.com/in/jasonlee-rothys",
    email: "j.lee@rothys.com",
    location: "San Francisco, CA",
    sector: "Apparel & Fashion",
    stage: "Researching",
    originSource: "Referral — David Kim",
    outreach: [
      { id: "o7", date: "2024-03-08", method: "LinkedIn", summary: "Viewed profile, gathering intel" },
    ],
    notes: "Sustainability angle — potential Everlane cross-intro",
  },
];
