// Sheet I/O for the /platform tab: portco KPI datapoints, saved AI content,
// and the competitive-radar watchlist.
//
// Conventions (matching the rest of the Sheets layer):
// - Reads NEVER call ensureTab — read paths stay write-free so browsing the
//   page can't mutate the workbook. A missing tab just reads as empty.
// - Writes ensureTab first, append in a single batched call, and audit via
//   logOpsEvent. All three tabs are append-only except explicit row deletes.

import {
  TAB_NAMES,
  fetchSheetTab,
  ensureTab,
  ensureHeaderWidth,
  appendSheetRow,
  appendSheetRows,
  deleteSheetRows,
  updateSheetCells,
  colLetters,
  logOpsEvent,
  buildPortfolioCompanies,
  buildTargets,
  appendTargetRows,
  type OpsLogAction,
  type TargetRowInput,
} from "./sheets.server";
import {
  callGeminiJSON,
  geminiGenerate,
  responseText,
  type GeminiPart,
  type GeminiResponse,
} from "./gemini.server";
import { runGemJSON } from "./gems/run";
import {
  execCoreGem,
  execLandscapeGem,
  execStrategyGem,
  boardArticleGem,
  mgmtQuestionsGem,
  thesisScreenGem,
} from "./gems/platform";
import {
  KPI_CATEGORIES,
  KPI_CATEGORY_LABELS,
  KPI_METRICS,
  currentPeriod,
  latestWins,
  metricCategory,
  metricDef,
  normalizePeriod,
  pointsForCompany,
  type ExtractedKpi,
  type KpiPasteAttachment,
  type KpiPoint,
  type NewKpiPoint,
} from "@/lib/platform-kpi";
import { extractDomain } from "@/lib/domain-utils";
import { searchPeople, enrichPerson } from "./apollo.server";
import { matchOrganization, isSumbleConfigured } from "./sumble.server";
import {
  MIN_FIT_SCORE,
  isMatchStatus,
  isThesisStatus,
  joinList,
  matchKeyOf,
  splitList,
  thesisCriteriaText,
  type NewThesis,
  type Thesis,
  type ThesisMatch,
  type ThesisMatchStatus,
  type ThesisStatus,
} from "@/lib/platform-thesis";
import {
  isContentType,
  type BoardArticlePayload,
  type DiligenceDimension,
  type DiligencePayload,
  type ExecBriefPayload,
  type MgmtQuestionsPayload,
  type NewRadarEntry,
  type PlatformContentPayload,
  type PlatformContentRow,
  type PlatformContentType,
  type RadarEntry,
} from "@/lib/platform-content";

/** C-suite / founder titles used when promoting a thesis match to Targets. */
const PROMOTE_TITLES = [
  "CEO",
  "CTO",
  "CIO",
  "CFO",
  "COO",
  "CISO",
  "CSO",
  "Founder",
  "Co-Founder",
  "Chief Executive Officer",
  "Chief Technology Officer",
  "Chief Information Officer",
  "Chief Financial Officer",
  "Chief Operating Officer",
  "Chief Information Security Officer",
  "Chief Strategy Officer",
  "Head of AI",
  "Head of Engineering",
];
const PROMOTE_SENIORITIES = ["c_suite", "founder"];
const PROMOTE_PER_COMPANY = 10;
/** Prefer true leaders when Apollo returns a mixed founding team. */
const LEADERSHIP_TITLE_RE =
  /\b(ceo|cto|cio|cfo|coo|ciso|cso|chief|founder|co-?founder|head of)\b/i;

export const PORTCO_KPI_HEADERS = [
  "ID",
  "PortCo URID",
  "Company Name",
  "Category",
  "Metric",
  "Period",
  "Value",
  "Unit",
  "Source",
  "Note",
  "Entered By",
  "Entered At",
];

// The payload is stored as JSON-in-a-cell. Google Sheets caps a single cell at
// 50,000 characters, and a rich venture-memo payload exceeds that — so the JSON
// is split across the primary "JSON" column plus the trailing "JSON 2".."JSON 5"
// overflow columns (appended at the END so existing rows keep their layout).
export const PLATFORM_CONTENT_HEADERS = [
  "ID",
  "Type",
  "Subject",
  "PortCo URID",
  "Title",
  "JSON",
  "Sources",
  "Generated At",
  "Generated By",
  "JSON 2",
  "JSON 3",
  "JSON 4",
  "JSON 5",
];

// Safe margin under Sheets' 50,000-char-per-cell limit.
const MAX_CELL_CHARS = 45000;
const JSON_OVERFLOW_COLS = ["json 2", "json 3", "json 4", "json 5"];

function chunkString(s: string, size: number): string[] {
  if (s.length <= size) return [s];
  const out: string[] = [];
  for (let i = 0; i < s.length; i += size) out.push(s.slice(i, i + size));
  return out;
}

export const RADAR_WATCHLIST_HEADERS = [
  "ID",
  "Company",
  "Website",
  "Segment",
  "Related PortCo URIDs",
  "Theme",
  "Note",
  "Added By",
  "Added At",
];

// ── Header-name-based row access (order-independent, like mapRows) ──

function headerIndex(rows: string[][]): Record<string, number> {
  const idx: Record<string, number> = {};
  (rows[0] ?? []).forEach((h, i) => {
    idx[h.trim().toLowerCase()] = i;
  });
  return idx;
}

function cell(row: string[], i: number | undefined): string {
  return i == null ? "" : (row[i] ?? "").trim();
}

async function readTab(tabName: string): Promise<string[][]> {
  // A tab that doesn't exist yet simply reads as empty.
  return fetchSheetTab(tabName).catch(() => [] as string[][]);
}

// ── PortCo KPIs ──────────────────────────────────────────────────

export async function buildPortcoKpis(): Promise<KpiPoint[]> {
  const rows = await readTab(TAB_NAMES.portcoKpis);
  if (rows.length < 2) return [];
  const h = headerIndex(rows);
  const points: KpiPoint[] = [];
  for (const row of rows.slice(1)) {
    const value = Number(cell(row, h["value"]).replace(/[$,%\s]/g, ""));
    const metric = cell(row, h["metric"]);
    if (!metric || !Number.isFinite(value)) continue;
    points.push({
      id: cell(row, h["id"]),
      portcoUrid: cell(row, h["portco urid"]),
      companyName: cell(row, h["company name"]),
      category: cell(row, h["category"]),
      metric,
      period: cell(row, h["period"]),
      value,
      unit: cell(row, h["unit"]),
      source: cell(row, h["source"]),
      note: cell(row, h["note"]),
      enteredBy: cell(row, h["entered by"]),
      enteredAt: cell(row, h["entered at"]),
    });
  }
  return points;
}

export interface AppendKpiOptions {
  action: OpsLogAction; // "edit" for manual adds, "import" for smart-paste, "enrich" for web
  source: string; // ops-log source, e.g. "platform-kpi" / "platform-digital"
  summary: string;
}

/**
 * Append datapoints in ONE batched write. Category and unit derive from the
 * KPI_METRICS registry; rows with unknown metrics or unparseable periods are
 * rejected up front so a bad smart-paste can't pollute the tab.
 * Pass `ops` to audit the write; omit it when the caller logs its own event.
 */
export async function appendKpiPoints(
  points: NewKpiPoint[],
  enteredBy: string,
  ops?: AppendKpiOptions,
): Promise<number> {
  const now = new Date().toISOString();
  const rows: string[][] = [];
  for (const p of points) {
    const def = metricDef(p.metric);
    if (!def) throw new Error(`Unknown KPI metric "${p.metric}"`);
    const period = normalizePeriod(p.period);
    if (!period) throw new Error(`Unparseable period "${p.period}" for ${def.label}`);
    if (!Number.isFinite(p.value)) throw new Error(`Invalid value for ${def.label}`);
    rows.push([
      crypto.randomUUID(),
      (p.portcoUrid ?? "").trim(),
      p.companyName.trim(),
      metricCategory(p.metric) ?? "",
      p.metric,
      period,
      String(p.value),
      def.unit,
      p.source,
      p.note ?? "",
      enteredBy,
      now,
    ]);
  }
  if (rows.length === 0) return 0;
  await ensureTab(TAB_NAMES.portcoKpis, PORTCO_KPI_HEADERS);
  await appendSheetRows(TAB_NAMES.portcoKpis, rows);
  if (ops) {
    await logOpsEvent({
      action: ops.action,
      source: ops.source,
      status: "ok",
      summary: ops.summary,
      records: rows.length,
      items: rows.map((r) => `${r[2]} · ${r[4]} = ${r[6]} (${r[5]})`),
    });
  }
  return rows.length;
}

export async function deleteKpiPoint(id: string): Promise<boolean> {
  const rows = await readTab(TAB_NAMES.portcoKpis);
  if (rows.length < 2) return false;
  const h = headerIndex(rows);
  const idx = rows.slice(1).findIndex((row) => cell(row, h["id"]) === id);
  if (idx === -1) return false;
  const target = rows[idx + 1];
  await deleteSheetRows(TAB_NAMES.portcoKpis, [idx + 2]);
  await logOpsEvent({
    action: "delete",
    source: "platform-kpi",
    status: "ok",
    summary: `Deleted KPI datapoint ${cell(target, h["metric"])} for ${cell(target, h["company name"])}`,
    records: 1,
  });
  return true;
}

// ── Platform Content (saved AI generations) ──────────────────────

const SOURCES_SEP = "\n";

export async function buildPlatformContent(
  type?: PlatformContentType,
): Promise<PlatformContentRow[]> {
  const rows = await readTab(TAB_NAMES.platformContent);
  if (rows.length < 2) return [];
  const h = headerIndex(rows);
  const out: PlatformContentRow[] = [];
  for (const row of rows.slice(1)) {
    const rowType = cell(row, h["type"]);
    if (!isContentType(rowType)) continue;
    if (type && rowType !== type) continue;
    let payload: PlatformContentPayload;
    try {
      // Reassemble the JSON from the primary cell + any overflow cells. Use raw
      // (untrimmed) access — cell() trims, which would corrupt a chunk boundary
      // that lands on whitespace inside a string value. Older rows have only the
      // primary "JSON" column; the overflow columns read as "".
      const rawCell = (name: string) => {
        const i = h[name];
        return i == null ? "" : (row[i] ?? "");
      };
      const json = rawCell("json") + JSON_OVERFLOW_COLS.map(rawCell).join("");
      payload = JSON.parse(json) as PlatformContentPayload;
    } catch {
      continue; // unparseable payloads are dropped, never fatal
    }
    out.push({
      id: cell(row, h["id"]),
      type: rowType,
      subject: cell(row, h["subject"]),
      portcoUrid: cell(row, h["portco urid"]),
      title: cell(row, h["title"]),
      payload,
      sources: cell(row, h["sources"]).split(SOURCES_SEP).map((s) => s.trim()).filter(Boolean),
      generatedAt: cell(row, h["generated at"]),
      generatedBy: cell(row, h["generated by"]),
    });
  }
  // Newest first — ISO timestamps sort lexicographically.
  return out.sort((a, b) => (a.generatedAt < b.generatedAt ? 1 : -1));
}

export interface SaveContentInput {
  type: PlatformContentType;
  subject: string;
  portcoUrid?: string;
  title: string;
  payload: PlatformContentPayload;
  sources: string[];
  generatedBy: string;
}

export async function savePlatformContent(input: SaveContentInput): Promise<PlatformContentRow> {
  const row: PlatformContentRow = {
    id: crypto.randomUUID(),
    type: input.type,
    subject: input.subject.trim(),
    portcoUrid: (input.portcoUrid ?? "").trim(),
    title: input.title.trim(),
    payload: input.payload,
    sources: input.sources,
    generatedAt: new Date().toISOString(),
    generatedBy: input.generatedBy,
  };
  await ensureTab(TAB_NAMES.platformContent, PLATFORM_CONTENT_HEADERS);
  // Existing tabs were created with the old 9-column header; extend it so the
  // overflow columns are addressable by name on read-back.
  await ensureHeaderWidth(TAB_NAMES.platformContent, PLATFORM_CONTENT_HEADERS);
  // Split the payload JSON across the primary + overflow cells to stay under the
  // 50k-char-per-cell limit.
  const chunks = chunkString(JSON.stringify(row.payload), MAX_CELL_CHARS);
  if (chunks.length > 1 + JSON_OVERFLOW_COLS.length) {
    throw new Error("Generated content is too large to store — try a narrower theme.");
  }
  const overflow = JSON_OVERFLOW_COLS.map((_, i) => chunks[i + 1] ?? "");
  await appendSheetRow(TAB_NAMES.platformContent, [
    row.id,
    row.type,
    row.subject,
    row.portcoUrid,
    row.title,
    chunks[0] ?? "",
    row.sources.join(SOURCES_SEP),
    row.generatedAt,
    row.generatedBy,
    ...overflow,
  ]);
  return row;
}

// ── Competitive Radar watchlist ──────────────────────────────────

const URID_SEP = ",";

export async function buildRadarWatchlist(): Promise<RadarEntry[]> {
  const rows = await readTab(TAB_NAMES.radarWatchlist);
  if (rows.length < 2) return [];
  const h = headerIndex(rows);
  return rows
    .slice(1)
    .filter((row) => cell(row, h["company"]))
    .map((row) => ({
      id: cell(row, h["id"]),
      company: cell(row, h["company"]),
      website: cell(row, h["website"]),
      segment: cell(row, h["segment"]),
      relatedPortcoUrids: cell(row, h["related portco urids"])
        .split(URID_SEP)
        .map((s) => s.trim())
        .filter(Boolean),
      theme: cell(row, h["theme"]),
      note: cell(row, h["note"]),
      addedBy: cell(row, h["added by"]),
      addedAt: cell(row, h["added at"]),
    }))
    .sort((a, b) => (a.addedAt < b.addedAt ? 1 : -1));
}

export async function addRadarEntry(input: NewRadarEntry, addedBy: string): Promise<RadarEntry> {
  const entry: RadarEntry = {
    id: crypto.randomUUID(),
    company: input.company.trim(),
    website: (input.website ?? "").trim(),
    segment: (input.segment ?? "").trim(),
    relatedPortcoUrids: input.relatedPortcoUrids ?? [],
    theme: (input.theme ?? "").trim(),
    note: (input.note ?? "").trim(),
    addedBy,
    addedAt: new Date().toISOString(),
  };
  if (!entry.company) throw new Error("Company name is required");
  await ensureTab(TAB_NAMES.radarWatchlist, RADAR_WATCHLIST_HEADERS);
  await appendSheetRow(TAB_NAMES.radarWatchlist, [
    entry.id,
    entry.company,
    entry.website,
    entry.segment,
    entry.relatedPortcoUrids.join(URID_SEP),
    entry.theme,
    entry.note,
    entry.addedBy,
    entry.addedAt,
  ]);
  await logOpsEvent({
    action: "edit",
    source: "platform-radar",
    status: "ok",
    summary: `Added "${entry.company}" to the competitive radar`,
    records: 1,
  });
  return entry;
}

export async function removeRadarEntry(id: string): Promise<boolean> {
  const rows = await readTab(TAB_NAMES.radarWatchlist);
  if (rows.length < 2) return false;
  const h = headerIndex(rows);
  const idx = rows.slice(1).findIndex((row) => cell(row, h["id"]) === id);
  if (idx === -1) return false;
  const company = cell(rows[idx + 1], h["company"]);
  await deleteSheetRows(TAB_NAMES.radarWatchlist, [idx + 2]);
  await logOpsEvent({
    action: "delete",
    source: "platform-radar",
    status: "ok",
    summary: `Removed "${company}" from the competitive radar`,
    records: 1,
  });
  return true;
}

// ══════════════════════════════════════════════════════════════
// AI layer — all on-demand (button-triggered), results persisted.
//
// Grounding rules:
// - Every URL that reaches the user comes from Gemini grounding metadata;
//   model-written URLs outside that set are dropped in code.
// - KNOWLEDGE fed to Gems is limited to user-entered KPI rows, stored
//   signals, Sheet-sourced company profiles, and grounded web results.
//   Asana-sourced fields NEVER reach a prompt (confidentiality wall —
//   note buildPortfolioCompanies is Sheet-sourced only by design).
// ══════════════════════════════════════════════════════════════

interface GroundedSource {
  /** Resolved publisher URL when we could follow the redirect; else the raw grounding URL. */
  uri: string;
  title: string;
  /** Human-readable host for display (e.g. "goldmansachs.com"). */
  domain?: string;
}

interface GroundedSearchResult {
  text: string;
  sources: GroundedSource[];
}

/** Bare hostname (no www.) for citation display; "" if the URL won't parse. */
function hostOf(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./i, "");
  } catch {
    return "";
  }
}

// Gemini grounding hands back ephemeral vertexaisearch "grounding-api-redirect"
// URLs — unreadable and short-lived. Follow the redirect once (bounded, best
// effort) to capture the durable publisher URL. Falls back to the redirect URL
// on any timeout/error so generation never blocks on citation resolution.
async function resolveGroundingUrl(uri: string): Promise<string> {
  if (!/grounding-api-redirect|vertexaisearch/i.test(uri)) return uri;
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 4500);
  try {
    const res = await fetch(uri, { method: "GET", redirect: "follow", signal: ctrl.signal });
    const finalUrl = res.url || uri;
    // We only want the resolved URL, not the page body.
    try {
      await res.body?.cancel();
    } catch {
      /* ignore */
    }
    return /grounding-api-redirect|vertexaisearch/i.test(finalUrl) ? uri : finalUrl;
  } catch {
    return uri;
  } finally {
    clearTimeout(timer);
  }
}

// Resolve a batch of grounding URLs to real publisher URLs and stamp a display
// domain on each, with bounded parallelism.
async function resolveSources(sources: GroundedSource[]): Promise<GroundedSource[]> {
  const CONCURRENCY = 12;
  for (let i = 0; i < sources.length; i += CONCURRENCY) {
    const slice = sources.slice(i, i + CONCURRENCY);
    const resolved = await Promise.all(slice.map((s) => resolveGroundingUrl(s.uri)));
    resolved.forEach((uri, j) => {
      slice[j].uri = uri;
      // When resolution failed the URL is still a Google redirect — its host is
      // useless for display, so fall back to the publisher title Gemini gave us.
      const stillRedirect = /grounding-api-redirect|vertexaisearch/i.test(uri);
      slice[j].domain = stillRedirect ? slice[j].title : hostOf(uri) || slice[j].title;
    });
  }
  return sources;
}

// Isolated google_search grounding call (the built-in tool can't be combined
// with JSON mode or custom functions, so the answer arrives as plain text).
async function groundedSearch(prompt: string, answerTokens = 1200): Promise<GroundedSearchResult> {
  let resp: GeminiResponse;
  try {
    resp = await geminiGenerate({
      contents: [{ role: "user", parts: [{ text: prompt }] }],
      tools: [{ googleSearch: {} }],
      generationConfig: {
        maxOutputTokens: answerTokens + 2048,
        thinkingConfig: { thinkingBudget: 2048 },
      },
    });
  } catch (e) {
    throw new Error(e instanceof Error ? e.message : "Web search failed");
  }
  const cand = resp.candidates?.[0];
  const text = (cand?.content?.parts || [])
    .filter((p) => typeof p.text === "string")
    .map((p) => p.text as string)
    .join("")
    .trim();
  const gm = cand?.groundingMetadata as
    | { groundingChunks?: Array<{ web?: { uri?: string; title?: string } }> }
    | undefined;
  const seen = new Set<string>();
  const sources: GroundedSource[] = [];
  for (const ch of gm?.groundingChunks || []) {
    const uri = ch?.web?.uri?.trim();
    if (uri && !seen.has(uri)) {
      seen.add(uri);
      sources.push({ uri, title: (ch?.web?.title || "").trim() });
    }
  }
  // Turn ephemeral redirect URLs into durable, readable publisher URLs.
  await resolveSources(sources);
  return { text, sources };
}

// Grounded calls return prose, so JSON inside must be dug out locally
// (gemini.server's extractor is private and tied to JSON-mode calls).
function extractJsonLoose(text: string): unknown | null {
  const cleaned = text.replace(/```(?:json)?/gi, "");
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start === -1 || end <= start) return null;
  try {
    return JSON.parse(cleaned.slice(start, end + 1));
  } catch {
    return null;
  }
}

function numberedSources(sources: GroundedSource[]): string {
  return sources
    .map((s, i) => {
      const label = [s.title, s.domain].filter(Boolean).join(" · ");
      return `[${i + 1}] ${label ? `${label} — ` : ""}${s.uri}`;
    })
    .join("\n");
}

// Ops-log wrapper for the generate flows: failures are audited too, then
// rethrown so the UI can toast them.
async function audited<T>(source: string, summary: string, fn: () => Promise<T>): Promise<T> {
  try {
    const result = await fn();
    await logOpsEvent({ action: "enrich", source, status: "ok", summary, records: 1 });
    return result;
  } catch (e) {
    await logOpsEvent({
      action: "enrich",
      source,
      status: "error",
      summary: `${summary} — ${e instanceof Error ? e.message : "failed"}`,
    });
    throw e;
  }
}

// ── KNOWLEDGE builders ───────────────────────────────────────────

interface SignalHeadline {
  date: string;
  company: string;
  category: string;
  signal: string;
}

// Light read of the stored Signals tab (header-aware) for grounding blocks.
async function readSignalHeadlines(
  filter: { company?: string; keywords?: string[] },
  limit: number,
): Promise<SignalHeadline[]> {
  const rows = await readTab(TAB_NAMES.signals);
  if (rows.length < 2) return [];
  const h = headerIndex(rows);
  const company = (filter.company ?? "").trim().toLowerCase();
  const keywords = (filter.keywords ?? []).map((k) => k.toLowerCase()).filter((k) => k.length > 3);
  const out: SignalHeadline[] = [];
  for (const row of rows.slice(1)) {
    const rowCompany = cell(row, h["company"]);
    const signal = cell(row, h["signal"]);
    if (!signal) continue;
    if (company && rowCompany.toLowerCase() !== company) continue;
    if (!company && keywords.length) {
      const hay = `${rowCompany} ${signal} ${cell(row, h["category"])}`.toLowerCase();
      if (!keywords.some((k) => hay.includes(k))) continue;
    }
    out.push({
      date: cell(row, h["date found"]),
      company: rowCompany,
      category: cell(row, h["category"]),
      signal,
    });
  }
  return out.sort((a, b) => (a.date < b.date ? 1 : -1)).slice(0, limit);
}

function headlineBlock(headlines: SignalHeadline[]): string {
  return headlines
    .map((s) => `- ${s.date ? `[${s.date}] ` : ""}${s.company}${s.category ? ` (${s.category})` : ""}: ${s.signal}`)
    .join("\n");
}

function themeKeywords(theme: string): string[] {
  return theme.toLowerCase().split(/[^a-z0-9+]+/).filter((w) => w.length > 3);
}

// ── KPI smart-paste extraction (no sheet write — user reviews first) ──

const EXTRACT_SYSTEM = `You extract portfolio-company KPI datapoints from pasted text AND/OR attached documents
(PDFs, slide decks, board packs, founder updates, emails, images of slides).

Read EVERY page / slide of each attachment carefully before extracting. Do not skim only the first page.

The ONLY metrics you may extract (use the exact key; convert values to the canonical unit):
${KPI_CATEGORIES.map((cat) =>
  KPI_METRICS[cat]
    .map((m) => `- ${m.key}: ${m.label}, unit ${m.unit}${m.unit === "$M" ? " (convert $4,200,000 or $4.2M to 4.2)" : ""}`)
    .join("\n"),
).join("\n")}

Rules:
- Extract ONLY numbers explicitly stated in the materials. Never estimate or invent a KPI value.
- For each item, "period" is when THAT number was measured if stated next to it (e.g. "Q3 2025", "Sep 2025", "2025-09"); null if that row doesn't say.
- "quote" is the VERBATIM sentence/fragment (or slide label) the number came from.
- Skip anything that doesn't map cleanly to a listed metric.

Document dating (required when attachments or dated materials are present):
- Read the full document for cover pages, footers, "as of", board date, quarter labels, filenames cues, and slide titles.
- Set "documentPeriod" to your best estimate of the reporting period the pack covers, as "YYYY-MM" when possible, or a clear label like "Q3 2025".
- Set "documentPeriodConfidence" to "high" | "medium" | "low".
- Set "documentPeriodEvidence" to a short note citing what you used (e.g. "Cover: Board meeting 12 Sep 2025"; "Footer Q3'25 on slides 4–11").
- If you truly cannot date the materials, set documentPeriod to null and confidence to "low".

Output ONLY JSON:
{"documentPeriod":null,"documentPeriodConfidence":"low","documentPeriodEvidence":"","items":[{"metric":"","value":0,"period":null,"quote":""}]}`;

export interface ExtractKpisResult {
  ok: boolean;
  items: ExtractedKpi[];
  error?: string;
  /** Best-effort reporting period for the whole pack (canonical YYYY-MM when possible). */
  documentPeriod?: string | null;
  documentPeriodConfidence?: "high" | "medium" | "low";
  documentPeriodEvidence?: string;
}

const KPI_INLINE_IMAGE = new Set(["image/png", "image/jpeg", "image/jpg", "image/gif", "image/webp"]);
const KPI_INLINE_TEXT = new Set(["text/plain", "text/csv", "text/markdown", "text/html"]);
const KPI_INLINE_DOC = new Set([
  "application/pdf",
  // Office — accepted when the model supports them; PDF is preferred for decks.
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-powerpoint",
  "application/msword",
]);

const MAX_KPI_ATTACH_BYTES = 12 * 1024 * 1024;
const MAX_KPI_ATTACHMENTS = 4;
const MAX_KPI_TEXT_CHARS = 20_000;

function buildKpiExtractParts(
  portcoName: string,
  text: string,
  attachments: KpiPasteAttachment[],
): { parts: GeminiPart[]; skipped: string[] } {
  const parts: GeminiPart[] = [];
  const skipped: string[] = [];
  const intro =
    `Company: ${portcoName}\n` +
    `Read all attached materials in full. Estimate the document's reporting date/period, then extract KPIs.\n`;
  const pasted = (text || "").trim();
  parts.push({
    text:
      intro +
      (pasted
        ? `\nPasted text / notes:\n${pasted.slice(0, 12000)}\n`
        : "\n(No pasted text — rely on the attached files.)\n"),
  });

  for (const a of attachments.slice(0, MAX_KPI_ATTACHMENTS)) {
    if (!a?.dataBase64 || !a.mimeType) {
      skipped.push(a?.filename || "unnamed");
      continue;
    }
    if (a.sizeBytes > MAX_KPI_ATTACH_BYTES) {
      skipped.push(`${a.filename} (too large)`);
      continue;
    }
    const mime = (a.mimeType || "").toLowerCase();
    if (KPI_INLINE_DOC.has(mime) || KPI_INLINE_IMAGE.has(mime)) {
      parts.push({ text: `\n--- Attachment: ${a.filename} (${mime}) ---` });
      parts.push({ inlineData: { mimeType: mime, data: a.dataBase64 } });
    } else if (KPI_INLINE_TEXT.has(mime) || mime.startsWith("text/")) {
      let decoded = "";
      try {
        decoded = Buffer.from(a.dataBase64, "base64").toString("utf8").slice(0, MAX_KPI_TEXT_CHARS);
      } catch {
        skipped.push(a.filename);
        continue;
      }
      parts.push({ text: `\n--- Attachment: ${a.filename} ---\n${decoded}` });
    } else {
      skipped.push(`${a.filename} (unsupported type ${mime || "unknown"})`);
    }
  }
  return { parts, skipped };
}

export async function extractKpisFromText(
  portco: { urid?: string; name: string },
  text: string,
  attachments: KpiPasteAttachment[] = [],
): Promise<ExtractKpisResult> {
  const hasText = !!(text || "").trim();
  const hasFiles = (attachments || []).length > 0;
  if (!hasText && !hasFiles) {
    return { ok: false, items: [], error: "Paste text or upload a document to extract from." };
  }

  const { parts, skipped } = buildKpiExtractParts(portco.name, text, attachments || []);
  if (parts.length <= 1 && !hasText) {
    return {
      ok: false,
      items: [],
      error:
        skipped.length > 0
          ? `Could not read attachments: ${skipped.join(", ")}. Prefer PDF exports of decks.`
          : "No readable content.",
    };
  }

  let rawText = "";
  try {
    const resp = await geminiGenerate({
      systemInstruction: { parts: [{ text: EXTRACT_SYSTEM }] },
      contents: [{ role: "user", parts }],
      generationConfig: {
        maxOutputTokens: 2500 + 2048,
        thinkingConfig: { thinkingBudget: 2048 },
        responseMimeType: "application/json",
      },
    });
    rawText = responseText(resp);
  } catch (e) {
    return {
      ok: false,
      items: [],
      error: e instanceof Error ? e.message : "Extraction failed",
    };
  }

  const parsed = (extractJsonLoose(rawText) ?? null) as {
    items?: ExtractedKpi[];
    documentPeriod?: string | null;
    documentPeriodConfidence?: string;
    documentPeriodEvidence?: string;
  } | null;

  if (!parsed) {
    return { ok: false, items: [], error: "Gemini returned malformed JSON." };
  }

  const items: ExtractedKpi[] = [];
  for (const raw of parsed.items ?? []) {
    const value = Number(raw?.value);
    if (!raw?.metric || !metricDef(raw.metric) || !Number.isFinite(value)) continue;
    const period = raw.period ? normalizePeriod(String(raw.period)) : null;
    items.push({
      metric: raw.metric,
      value,
      period,
      quote: String(raw.quote ?? "").slice(0, 300),
    });
  }

  const docPeriodRaw = parsed.documentPeriod != null ? String(parsed.documentPeriod) : "";
  const documentPeriod = docPeriodRaw ? normalizePeriod(docPeriodRaw) || docPeriodRaw.trim() || null : null;
  const confRaw = String(parsed.documentPeriodConfidence || "low").toLowerCase();
  const documentPeriodConfidence =
    confRaw === "high" || confRaw === "medium" || confRaw === "low" ? confRaw : "low";

  return {
    ok: true,
    items,
    documentPeriod,
    documentPeriodConfidence,
    documentPeriodEvidence: String(parsed.documentPeriodEvidence || "").slice(0, 400),
    ...(skipped.length
      ? { error: `Skipped: ${skipped.join(", ")}` }
      : {}),
  };
}

// ── Digital-traction web refresh ─────────────────────────────────

const DIGITAL_KEYS = KPI_METRICS.digital.map((m) => m.key);

export interface DigitalTractionResult {
  added: number;
  points: NewKpiPoint[];
  evidence: GroundedSource[];
  note: string;
}

export async function fetchDigitalTraction(
  portco: { urid?: string; name: string; website?: string },
  enteredBy: string,
): Promise<DigitalTractionResult> {
  return audited("platform-digital", `Web refresh: digital traction for ${portco.name}`, async () => {
    const site = portco.website ? ` (website: ${portco.website})` : "";
    const { text, sources } = await groundedSearch(
      `Search the web for current public digital-presence stats of the company "${portco.name}"${site}. ` +
        `Find: LinkedIn follower count, X (Twitter) follower count, number of press/news mentions in the last 90 days, ` +
        `and global web-traffic rank. End your answer with ONLY this JSON (null for anything you could not find; ` +
        `never guess): {"linkedin_followers":null,"x_followers":null,"press_mentions_90d":null,"traffic_rank_global":null}`,
      900,
    );
    // No grounding chunks = nothing verifiable — store nothing.
    if (sources.length === 0) {
      return { added: 0, points: [], evidence: [], note: "No grounded web results found." };
    }
    const parsed = (extractJsonLoose(text) ?? {}) as Record<string, unknown>;
    const evidenceNote = `web · ${sources.slice(0, 2).map((s) => s.uri).join(" ")}`;
    const period = currentPeriod();
    const points: NewKpiPoint[] = [];
    for (const key of DIGITAL_KEYS) {
      const value = Number(parsed[key]);
      if (parsed[key] == null || !Number.isFinite(value) || value < 0) continue;
      points.push({
        portcoUrid: portco.urid ?? "",
        companyName: portco.name,
        metric: key,
        period,
        value,
        source: "gemini_web",
        note: evidenceNote,
      });
    }
    // No ops arg: the surrounding audited() wrapper writes the single
    // enrich log entry for this refresh.
    if (points.length > 0) await appendKpiPoints(points, enteredBy);
    return {
      added: points.length,
      points,
      evidence: sources.slice(0, 5),
      note:
        points.length === 0
          ? "Search ran but no verifiable numbers were found."
          : `Best-effort public data — ${points.length} of ${DIGITAL_KEYS.length} metrics found.`,
    };
  });
}

// ── Public valuation web refresh ─────────────────────────────────
// Complements Asana DTC Ownership / Investment with best-effort public
// post-money and last-round figures. Values must be in USD millions.

const VALUATION_KEYS = ["post_money_usd_m", "last_round_usd_m"] as const;

export async function fetchPublicValuation(
  portco: { urid?: string; name: string; website?: string },
  enteredBy: string,
): Promise<DigitalTractionResult> {
  return audited("platform-valuation", `Web refresh: valuation for ${portco.name}`, async () => {
    const site = portco.website ? ` (website: ${portco.website})` : "";
    const { text, sources } = await groundedSearch(
      `Search the web for the most recent publicly reported funding valuation of the company "${portco.name}"${site}. ` +
        `Prefer post-money valuation and last round size from Crunchbase, PitchBook summaries, TechCrunch, or company press releases. ` +
        `Convert all dollar amounts to millions of USD (e.g. $50,000,000 → 50). ` +
        `End your answer with ONLY this JSON (null for anything you could not verify; never guess): ` +
        `{"post_money_usd_m":null,"last_round_usd_m":null}`,
      900,
    );
    if (sources.length === 0) {
      return { added: 0, points: [], evidence: [], note: "No grounded web results found for valuation." };
    }
    const parsed = (extractJsonLoose(text) ?? {}) as Record<string, unknown>;
    const evidenceNote = `web · ${sources.slice(0, 2).map((s) => s.uri).join(" ")}`;
    const period = currentPeriod();
    const points: NewKpiPoint[] = [];
    for (const key of VALUATION_KEYS) {
      const value = Number(parsed[key]);
      if (parsed[key] == null || !Number.isFinite(value) || value <= 0) continue;
      points.push({
        portcoUrid: portco.urid ?? "",
        companyName: portco.name,
        metric: key,
        period,
        value,
        source: "gemini_web",
        note: evidenceNote,
      });
    }
    if (points.length > 0) await appendKpiPoints(points, enteredBy);
    return {
      added: points.length,
      points,
      evidence: sources.slice(0, 5),
      note:
        points.length === 0
          ? "Search ran but no verifiable valuation figures were found."
          : `Best-effort public valuation — ${points.length} metric(s) saved.`,
    };
  });
}

// ── Executive brief (venture-intelligence memo) ──────────────────
//
// A partner-grade memo assembled from FOUR grounded searches feeding THREE
// focused synthesis Gems (core / landscape / strategy) that run in parallel and
// merge into one payload. Splitting the synthesis keeps every JSON completion
// inside its token budget (one monolithic call truncated the tail) and lets each
// prompt stay sharp. All URLs across the four searches share one citation pool.

// Loose shapes for the three Gem outputs (every field optional; sanitized on merge).
type CoreOut = {
  thesis?: string;
  atAGlance?: {
    stageAttractiveness?: number;
    marketMaturity?: string;
    capitalIntensity?: string;
    competitiveDensity?: string;
    exitWindow?: string;
    convictionScore?: number;
  };
  scorecard?: { category?: string; score?: number; note?: string }[];
  whyNow?: { driver?: string; detail?: string; sourceUrl?: string }[];
  marketDynamics?: Record<string, string>;
  marketSizing?: {
    narrative?: string;
    figures?: { label?: string; value?: string; sourceUrl?: string }[];
  };
  enterpriseAngle?: { area?: string; whyItMatters?: string }[];
  keyDevelopments?: { point?: string; detail?: string; sourceUrl?: string }[];
};
type LandscapeOut = {
  competitiveLandscape?: {
    category?: string;
    companies?: { company?: string; note?: string; tier?: string; sourceUrl?: string }[];
  }[];
  fundingLandscape?: {
    summary?: string;
    largestRounds?: {
      company?: string;
      amount?: string;
      stage?: string;
      investors?: string;
      sourceUrl?: string;
    }[];
    activeInvestors?: string[];
    recentAcquisitions?: { detail?: string; sourceUrl?: string }[];
    benchmarks?: { label?: string; value?: string }[];
  };
  founderMap?: {
    company?: string;
    founders?: string;
    background?: string;
    location?: string;
    investors?: string;
    sourceUrl?: string;
  }[];
  valueChain?: { layer?: string; description?: string; players?: string }[];
  prospectiveCompanies?: {
    company?: string;
    stage?: string;
    whatTheyDo?: string;
    whyFits?: string;
    sourceUrl?: string;
  }[];
  openSource?: { project?: string; detail?: string; sourceUrl?: string }[];
  exitLandscape?: {
    note?: string;
    likelyAcquirers?: string[];
    ipoCandidates?: string[];
    recentDeals?: { detail?: string; sourceUrl?: string }[];
  };
};
type StrategyOut = {
  whiteSpace?: {
    opportunity?: string;
    rationale?: string;
    category?: string;
    confidence?: string;
  }[];
  investHere?: { area?: string; conviction?: number; rationale?: string }[];
  avoidHere?: { area?: string; reason?: string }[];
  scenarios?: { bull?: string; base?: string; bear?: string };
  technicalRisks?: string[];
  commercialRisks?: string[];
  regulatoryRisks?: string[];
  metricsToWatch?: string[];
  recommendedActions?: { action?: string; category?: string; entities?: string[] }[];
  portfolioImplications?: { company?: string; implication?: string }[];
  watchlistSuggestions?: string[];
};

export async function generateExecBrief(
  theme: string,
  generatedBy: string,
): Promise<PlatformContentRow> {
  return audited("platform-research", `Generated executive brief — ${theme}`, async () => {
    // Four grounded searches feed the memo.
    const [research, marketStudy, funding, earlyStage] = await Promise.all([
      groundedSearch(
        `Research recent developments (last 6–12 months) in: ${theme}. ` +
          `Cover market shifts, major product launches, research breakthroughs, and the "why now" inflections ` +
          `(technology breakthroughs, cost declines, regulation, economic/behavioral shifts, infrastructure, labor). ` +
          `Map the competitive field into sub-sectors, and describe the value chain / ecosystem stack from applications down to compute/silicon. ` +
          `Be factual and specific.`,
        1800,
      ).catch(() => ({ text: "", sources: [] }) as GroundedSearchResult),
      groundedSearch(
        `Provide a market study for: ${theme} with specific figures and sources where reported: ` +
          `(1) market sizing — TAM / SAM / SOM, current market value, and CAGR / growth forecast with the year; ` +
          `(2) market dynamics — who owns the budget, the buying cycle, existing vs. net-new spend, the adoption curve, ` +
          `procurement friction, replacement vs. net-new market, and unit economics; ` +
          `(3) enterprise adoption — which use cases have the strongest enterprise budget, ROI, or compliance drivers. ` +
          `Do not estimate figures that are not reported.`,
        1600,
      ).catch(() => ({ text: "", sources: [] }) as GroundedSearchResult),
      groundedSearch(
        `Analyze the venture funding landscape for: ${theme}. Report with sources: ` +
          `the largest recent financing rounds (company, amount, stage, lead investors); the most active investors leading deals; ` +
          `recent acquisitions and M&A; typical seed and Series A round sizes and valuations; exit multiples and any IPO activity or candidates. ` +
          `Cite concrete numbers; do not invent figures.`,
        1500,
      ).catch(() => ({ text: "", sources: [] }) as GroundedSearchResult),
      groundedSearch(
        `Find early-stage startups (Seed, Series A, or Series B — including notable stealth, YC, or accelerator companies) building in: ${theme}. ` +
          `For each: name, what it builds, latest stage and round size, and lead investors. Also report the FOUNDERS and their backgrounds ` +
          `(prior companies, research labs, notable pedigree) for the most important companies, and any high-traction open-source projects, ` +
          `models, benchmarks, or research efforts in this space. Only include companies whose stage you can verify.`,
        1500,
      ).catch(() => ({ text: "", sources: [] }) as GroundedSearchResult),
    ]);
    const [portcos, radar, headlines] = await Promise.all([
      buildPortfolioCompanies().catch(() => []),
      buildRadarWatchlist().catch(() => [] as RadarEntry[]),
      readSignalHeadlines({ keywords: themeKeywords(theme) }, 12),
    ]);
    const keywords = themeKeywords(theme);
    const radarRows = radar.filter(
      (r) => !r.theme || keywords.some((k) => r.theme.toLowerCase().includes(k)),
    );

    // Shared KNOWLEDGE blocks.
    const kb = (label: string, s: GroundedSearchResult) => ({
      label,
      content: s.text ? `${s.text}\n\nSources:\n${numberedSources(s.sources)}` : "",
    });
    const researchKB = kb("WEB RESEARCH (grounded — developments, why-now, value chain)", research);
    const marketKB = kb(
      "MARKET STUDY (grounded — sizing, dynamics, enterprise adoption)",
      marketStudy,
    );
    const fundingKB = kb(
      "FUNDING LANDSCAPE (grounded — rounds, investors, M&A, benchmarks)",
      funding,
    );
    const earlyKB = kb(
      "EARLY-STAGE & FOUNDERS (grounded — Seed–B, founders, open source)",
      earlyStage,
    );
    const signalsKB = { label: "RELATED STORED SIGNALS", content: headlineBlock(headlines) };
    const radarKB = {
      label: "COMPETITIVE RADAR (watchlist)",
      content: radarRows
        .slice(0, 15)
        .map(
          (r) =>
            `- ${r.company}${r.segment ? ` [${r.segment}]` : ""}${r.note ? `: ${r.note}` : ""}`,
        )
        .join("\n"),
    };
    const portfolioKB = {
      label: "PORTFOLIO (our companies — never list as prospects; cite by name for implications)",
      content: portcos
        .slice(0, 30)
        .map((p) => `- ${p.name} [${p.domain}] ${p.description?.slice(0, 160) ?? ""}`)
        .join("\n"),
    };

    // Three focused syntheses in parallel.
    const userPrompt = `Theme: ${theme}`;
    const [coreRes, landRes, stratRes] = await Promise.all([
      runGemJSON<CoreOut>(execCoreGem, userPrompt, [researchKB, marketKB, signalsKB]),
      runGemJSON<LandscapeOut>(execLandscapeGem, userPrompt, [
        researchKB,
        fundingKB,
        earlyKB,
        portfolioKB,
      ]),
      runGemJSON<StrategyOut>(execStrategyGem, userPrompt, [
        researchKB,
        marketKB,
        fundingKB,
        earlyKB,
        radarKB,
        portfolioKB,
      ]),
    ]);
    if (!coreRes.ok && !landRes.ok && !stratRes.ok) {
      throw new Error(coreRes.error || "Brief generation failed");
    }
    const core = coreRes.data ?? {};
    const land = landRes.data ?? {};
    const strat = stratRes.data ?? {};

    // One citation pool across all four searches.
    const allSources = [
      ...research.sources,
      ...marketStudy.sources,
      ...funding.sources,
      ...earlyStage.sources,
    ];
    const norm = (u: string) =>
      (u || "")
        .trim()
        .replace(/[#?].*$/, "")
        .replace(/\/+$/, "")
        .toLowerCase();
    const metaByUrl = new Map<string, GroundedSource>();
    for (const s of allSources) if (!metaByUrl.has(norm(s.uri))) metaByUrl.set(norm(s.uri), s);
    const usedUrls = new Set<string>();
    const cite = (u?: string): string => {
      const hit = metaByUrl.get(norm(u || ""));
      if (!hit) return "";
      usedUrls.add(hit.uri);
      return hit.uri;
    };
    const clampInt = (n: unknown, lo: number, hi: number) =>
      Math.max(lo, Math.min(hi, Math.round(Number(n) || 0)));
    const str = (v: unknown) => (typeof v === "string" ? v.trim() : "");
    const strList = (a: unknown, max: number) =>
      (Array.isArray(a) ? a : []).map(str).filter(Boolean).slice(0, max);
    const portcoNameSet = new Set(portcos.map((p) => p.name.trim().toLowerCase()));

    // ── core ──
    const scorecard = (core.scorecard ?? [])
      .filter((s) => str(s?.category))
      .map((s) => ({
        category: str(s.category),
        score: clampInt(s.score, 1, 10),
        note: str(s.note),
      }))
      .slice(0, 12);
    const rawGlance = core.atAGlance;
    const atAGlance = rawGlance
      ? {
          stageAttractiveness: clampInt(rawGlance.stageAttractiveness, 0, 5) || undefined,
          marketMaturity: str(rawGlance.marketMaturity),
          capitalIntensity: str(rawGlance.capitalIntensity),
          competitiveDensity: str(rawGlance.competitiveDensity),
          exitWindow: str(rawGlance.exitWindow),
          convictionScore:
            Number.isFinite(Number(rawGlance.convictionScore)) &&
            Number(rawGlance.convictionScore) > 0
              ? Math.max(0, Math.min(10, Math.round(Number(rawGlance.convictionScore) * 10) / 10))
              : undefined,
        }
      : undefined;
    const whyNow = (core.whyNow ?? [])
      .filter((w) => str(w?.driver))
      .map((w) => ({ driver: str(w.driver), detail: str(w.detail), sourceUrl: cite(w.sourceUrl) }))
      .slice(0, 6);
    const rawDyn = core.marketDynamics ?? {};
    const dynKeys = [
      "budgetOwners",
      "buyingCycle",
      "existingSpend",
      "newSpend",
      "adoptionCurve",
      "procurementFriction",
      "replacementVsNetNew",
      "unitEconomics",
      "purchasingDrivers",
    ] as const;
    const marketDynamics =
      str(rawDyn.narrative) || dynKeys.some((k) => str(rawDyn[k]))
        ? {
            narrative: str(rawDyn.narrative),
            ...Object.fromEntries(dynKeys.map((k) => [k, str(rawDyn[k])])),
          }
        : undefined;
    const marketSizing = core.marketSizing
      ? {
          narrative: str(core.marketSizing.narrative),
          figures: (core.marketSizing.figures ?? [])
            .filter((f) => str(f?.label) && str(f?.value))
            .map((f) => ({
              label: str(f.label),
              value: str(f.value),
              sourceUrl: cite(f.sourceUrl),
            }))
            .slice(0, 10),
        }
      : undefined;
    const enterpriseAngle = (core.enterpriseAngle ?? [])
      .filter((e) => str(e?.area))
      .map((e) => ({ area: str(e.area), whyItMatters: str(e.whyItMatters) }))
      .slice(0, 6);
    const keyDevelopments = (core.keyDevelopments ?? [])
      .filter((d) => str(d?.point))
      .map((d) => ({ point: str(d.point), detail: str(d.detail), sourceUrl: cite(d.sourceUrl) }))
      .slice(0, 8);

    // ── landscape ──
    const competitiveLandscape = (land.competitiveLandscape ?? [])
      .filter((g) => str(g?.category) && Array.isArray(g?.companies))
      .map((g) => ({
        category: str(g.category),
        companies: (g.companies ?? [])
          .filter((c) => str(c?.company))
          .map((c) => ({
            company: str(c.company),
            note: str(c.note),
            tier: str(c.tier),
            sourceUrl: cite(c.sourceUrl) || undefined,
          }))
          .slice(0, 12),
      }))
      .filter((g) => g.companies.length > 0)
      .slice(0, 8);
    const rawFund = land.fundingLandscape;
    const fundingLandscape = rawFund
      ? {
          summary: str(rawFund.summary),
          largestRounds: (rawFund.largestRounds ?? [])
            .filter((r) => str(r?.company))
            .map((r) => ({
              company: str(r.company),
              amount: str(r.amount),
              stage: str(r.stage),
              investors: str(r.investors),
              sourceUrl: cite(r.sourceUrl) || undefined,
            }))
            .slice(0, 10),
          activeInvestors: strList(rawFund.activeInvestors, 12),
          recentAcquisitions: (rawFund.recentAcquisitions ?? [])
            .filter((a) => str(a?.detail))
            .map((a) => ({ detail: str(a.detail), sourceUrl: cite(a.sourceUrl) || undefined }))
            .slice(0, 8),
          benchmarks: (rawFund.benchmarks ?? [])
            .filter((b) => str(b?.label) && str(b?.value))
            .map((b) => ({ label: str(b.label), value: str(b.value) }))
            .slice(0, 8),
        }
      : undefined;
    const founderMap = (land.founderMap ?? [])
      .filter((f) => str(f?.company) && str(f?.founders))
      .map((f) => ({
        company: str(f.company),
        founders: str(f.founders),
        background: str(f.background),
        location: str(f.location),
        investors: str(f.investors),
        sourceUrl: cite(f.sourceUrl) || undefined,
      }))
      .slice(0, 10);
    const valueChain = (land.valueChain ?? [])
      .filter((l) => str(l?.layer))
      .map((l) => ({
        layer: str(l.layer),
        description: str(l.description),
        players: str(l.players),
      }))
      .slice(0, 10);
    const prospectiveCompanies = (land.prospectiveCompanies ?? [])
      .filter(
        (c) =>
          str(c?.company) &&
          !portcoNameSet.has(str(c.company).toLowerCase()) &&
          /\b(pre-?seed|seed|series\s*[ab])\b/i.test(c.stage ?? ""),
      )
      .map((c) => ({
        company: str(c.company),
        stage: str(c.stage),
        whatTheyDo: str(c.whatTheyDo),
        whyFits: str(c.whyFits),
        sourceUrl: cite(c.sourceUrl),
      }))
      .slice(0, 12);
    const openSource = (land.openSource ?? [])
      .filter((o) => str(o?.project))
      .map((o) => ({
        project: str(o.project),
        detail: str(o.detail),
        sourceUrl: cite(o.sourceUrl) || undefined,
      }))
      .slice(0, 6);
    const rawExit = land.exitLandscape;
    const exitLandscape =
      rawExit &&
      (str(rawExit.note) ||
        (rawExit.likelyAcquirers?.length ?? 0) ||
        (rawExit.ipoCandidates?.length ?? 0) ||
        (rawExit.recentDeals?.length ?? 0))
        ? {
            note: str(rawExit.note),
            likelyAcquirers: strList(rawExit.likelyAcquirers, 12),
            ipoCandidates: strList(rawExit.ipoCandidates, 12),
            recentDeals: (rawExit.recentDeals ?? [])
              .filter((d) => str(d?.detail))
              .map((d) => ({ detail: str(d.detail), sourceUrl: cite(d.sourceUrl) || undefined }))
              .slice(0, 8),
          }
        : undefined;

    // ── strategy ──
    const confidenceOf = (c?: string): "high" | "medium" | "speculative" =>
      c === "high" || c === "speculative" ? c : "medium";
    const whiteSpace = (strat.whiteSpace ?? [])
      .filter((w) => str(w?.opportunity))
      .map((w) => ({
        opportunity: str(w.opportunity),
        rationale: str(w.rationale),
        category: str(w.category),
        confidence: confidenceOf(w.confidence),
      }))
      .slice(0, 8);
    const investHere = (strat.investHere ?? [])
      .filter((i) => str(i?.area))
      .map((i) => ({
        area: str(i.area),
        conviction: clampInt(i.conviction, 1, 5),
        rationale: str(i.rationale),
      }))
      .slice(0, 8);
    const avoidHere = (strat.avoidHere ?? [])
      .filter((a) => str(a?.area))
      .map((a) => ({ area: str(a.area), reason: str(a.reason) }))
      .slice(0, 8);
    const rawScen = strat.scenarios;
    const scenarios =
      rawScen && (str(rawScen.bull) || str(rawScen.base) || str(rawScen.bear))
        ? { bull: str(rawScen.bull), base: str(rawScen.base), bear: str(rawScen.bear) }
        : undefined;
    const recommendedActions = (strat.recommendedActions ?? [])
      .filter((a) => str(a?.action))
      .map((a) => ({
        action: str(a.action),
        category: str(a.category),
        entities: strList(a.entities, 8),
      }))
      .slice(0, 10);
    const portfolioImplications = (strat.portfolioImplications ?? [])
      .filter((x) => str(x?.company))
      .map((x) => ({ company: str(x.company), implication: str(x.implication) }))
      .slice(0, 10);

    // Readable citation labels (publisher + domain) for every referenced source.
    const sourceMeta = [...usedUrls].map((url) => {
      const m = metaByUrl.get(norm(url));
      return { url, title: m?.title ?? "", domain: m?.domain ?? hostOf(url) };
    });
    const payload: ExecBriefPayload = {
      thesis: str(core.thesis),
      tldr: str(core.thesis), // legacy field mirrors the thesis for older readers
      atAGlance,
      scorecard,
      whyNow,
      marketDynamics,
      marketSizing,
      enterpriseAngle,
      competitiveLandscape,
      fundingLandscape,
      founderMap,
      valueChain,
      whiteSpace,
      investHere,
      avoidHere,
      keyDevelopments,
      prospectiveCompanies,
      openSource,
      technicalRisks: strList(strat.technicalRisks, 6),
      commercialRisks: strList(strat.commercialRisks, 6),
      regulatoryRisks: strList(strat.regulatoryRisks, 6),
      exitLandscape,
      metricsToWatch: strList(strat.metricsToWatch, 10),
      scenarios,
      recommendedActions,
      portfolioImplications,
      watchlistSuggestions: strList(strat.watchlistSuggestions, 12),
      sources: [...usedUrls],
      sourceMeta,
    };
    return savePlatformContent({
      type: "exec_brief",
      subject: theme,
      title: `Executive brief — ${theme}`,
      payload,
      sources: payload.sources.length ? payload.sources : allSources.map((s) => s.uri),
      generatedBy,
    });
  });
}

// ── Board reading list ───────────────────────────────────────────

export async function generateBoardArticles(
  theme: string,
  generatedBy: string,
): Promise<PlatformContentRow> {
  return audited("platform-board", `Curated board reading — ${theme}`, async () => {
    const [news, analysis] = await Promise.all([
      groundedSearch(
        `Find the most substantive recent news articles about: ${theme}. For each, give the headline and what it reports.`,
        900,
      ),
      groundedSearch(
        `Find in-depth analysis pieces, essays, or reports about: ${theme}. For each, give the title and core argument.`,
        900,
      ),
    ]);
    const harvested = new Map<string, GroundedSource>();
    for (const s of [...news.sources, ...analysis.sources]) harvested.set(s.uri, s);
    if (harvested.size === 0) throw new Error("No grounded articles found for this theme");
    const articleList = [...harvested.values()];
    const res = await runGemJSON<BoardArticlePayload>(
      boardArticleGem,
      `Curate a board reading list on: ${theme}`,
      [
        {
          label: "ARTICLES (the only ones you may pick from)",
          content: numberedSources(articleList),
        },
        {
          label: "WHAT THE COVERAGE SAYS",
          content: `${news.text}\n\n${analysis.text}`.trim(),
        },
      ],
    );
    if (!res.ok || !res.data) throw new Error(res.error || "Curation failed");
    const articles = (res.data.articles ?? [])
      .filter((a) => a?.url && harvested.has(a.url))
      .slice(0, 6)
      .map((a) => ({
        title: a.title || harvested.get(a.url)?.title || a.url,
        url: a.url,
        whyRead: a.whyRead ?? "",
      }));
    if (articles.length === 0) throw new Error("Curation returned no verifiable articles");
    const payload: BoardArticlePayload = { digest: res.data.digest ?? "", articles };
    return savePlatformContent({
      type: "board_article",
      subject: theme,
      title: `Board reading — ${theme}`,
      payload,
      sources: articles.map((a) => a.url),
      generatedBy,
    });
  });
}

// ── Questions for management ─────────────────────────────────────

function kpiKnowledgeBlock(points: KpiPoint[]): string {
  const current = latestWins(points);
  const lines: string[] = [];
  for (const cat of KPI_CATEGORIES) {
    const catLines: string[] = [];
    for (const def of KPI_METRICS[cat]) {
      const series = current
        .filter((p) => p.metric === def.key)
        .sort((a, b) => (a.period < b.period ? -1 : 1));
      if (series.length === 0) {
        catLines.push(`- ${def.label}: NO DATA`);
        continue;
      }
      const latest = series[series.length - 1];
      const prev = series.length > 1 ? series[series.length - 2] : null;
      const delta = prev
        ? ` (was ${prev.value} ${prev.unit} in ${prev.period}, change ${latest.value - prev.value >= 0 ? "+" : ""}${(latest.value - prev.value).toFixed(2)})`
        : " (single datapoint — no trend yet)";
      catLines.push(`- ${def.label}: ${latest.value} ${latest.unit} in ${latest.period}${delta}`);
    }
    lines.push(`${KPI_CATEGORY_LABELS[cat]}:\n${catLines.join("\n")}`);
  }
  return lines.join("\n\n");
}

export async function generateMgmtQuestions(
  portco: { urid?: string; name: string },
  generatedBy: string,
): Promise<PlatformContentRow> {
  return audited("platform-questions", `Generated management questions — ${portco.name}`, async () => {
    const [allKpis, portcos, headlines] = await Promise.all([
      buildPortcoKpis(),
      buildPortfolioCompanies().catch(() => []),
      readSignalHeadlines({ company: portco.name }, 8),
    ]);
    const kpis = pointsForCompany(allKpis, { urid: portco.urid, name: portco.name });
    // Sheet-sourced profile only — buildPortfolioCompanies never carries
    // Asana fields, which keeps the confidentiality wall intact.
    const profile = portcos.find(
      (p) =>
        (portco.urid && p.urid === portco.urid) ||
        p.name.trim().toLowerCase() === portco.name.trim().toLowerCase(),
    );
    const res = await runGemJSON<MgmtQuestionsPayload>(
      mgmtQuestionsGem,
      `Prepare questions for a management check-in with ${portco.name}.`,
      [
        { label: "KPI DATA (latest per metric, with prior-period deltas)", content: kpiKnowledgeBlock(kpis) },
        { label: "RECENT SIGNALS", content: headlineBlock(headlines) },
        {
          label: "COMPANY PROFILE (sheet-sourced)",
          content: profile
            ? `${profile.name} — ${profile.sector || profile.domain}${profile.location ? ` · ${profile.location}` : ""}${profile.website ? ` · ${profile.website}` : ""}\n${profile.description ?? ""}`
            : portco.name,
        },
      ],
    );
    if (!res.ok || !res.data) throw new Error(res.error || "Question generation failed");
    const payload: MgmtQuestionsPayload = {
      questions: (res.data.questions ?? []).filter((q) => q?.question),
    };
    if (payload.questions.length === 0) throw new Error("No questions generated");
    return savePlatformContent({
      type: "mgmt_questions",
      subject: portco.name,
      portcoUrid: portco.urid,
      title: `Management questions — ${portco.name}`,
      payload,
      sources: [],
      generatedBy,
    });
  });
}

// ── Diligence run ────────────────────────────────────────────────

export async function runDiligence(
  company: string,
  website: string | undefined,
  generatedBy: string,
): Promise<PlatformContentRow> {
  return audited("platform-diligence", `Diligence run — ${company}`, async () => {
    const site = website ? ` (website: ${website})` : "";
    // Stored Signal Radar rows for this company are part of the findings too —
    // exact company match first, then a name-mention fallback across all rows.
    const signalsPromise = readSignalHeadlines({ company }, 10).then(async (exact) => {
      if (exact.length > 0 || company.trim().length <= 3) return exact;
      return readSignalHeadlines({ keywords: [company.trim().toLowerCase()] }, 10);
    });
    const [research, signalHeadlines] = await Promise.all([
      groundedSearch(
        `Research the company "${company}"${site}: what the product/technology is, funding history and investors, ` +
          `target market and business model, main competitors, traction or notable customers, and founding team. ` +
          `Be factual; say clearly when something could not be found.`,
        1500,
      ),
      signalsPromise.catch(() => [] as SignalHeadline[]),
    ]);
    if (!research.text) throw new Error("Web research returned nothing for this company");
    const internal = signalHeadlines.length
      ? `\n\nINTERNAL SIGNAL RADAR (already tracked in VenturePulse):\n${headlineBlock(signalHeadlines)}`
      : "";
    const findings = `${research.text}${internal}\n\nSources:\n${numberedSources(research.sources)}`;
    // One Vertex call for score + questions (was two) — cuts diligence quota use ~33%.
    const scored = await callGeminiJSON<{
      score?: number;
      dimensions?: Array<{ name?: string; score?: number; note?: string }>;
      rationale?: string;
      questions?: MgmtQuestionsPayload["questions"];
    }>(
      [
        "You are diligence support for a deep-tech VC (security, AI, data, cloud, infrastructure, silicon, supply chain).",
        "Score ONLY from the provided findings; do not invent facts.",
        "Also draft management questions grounded in findings / weak dimensions — no generic questionnaires.",
        'Group questions by area ("Product", "Market", "Traction", "Team", or "Risks").',
        'Output ONLY JSON: {"score":<1-10>,"dimensions":[{"name":"","score":<1-10>,"note":""}],"rationale":"","questions":[{"area":"","question":"","why":""}]}',
      ].join(" "),
      `Company: ${company}\n\nFindings:\n${findings}`,
      2048,
    );
    if (!scored.ok || !scored.data) throw new Error(scored.error || "Thesis scoring failed");
    const dimensions: DiligenceDimension[] = Array.isArray(scored.data.dimensions)
      ? scored.data.dimensions
          .map((d) => ({
            name: String(d?.name ?? ""),
            score: Number(d?.score ?? 0),
            note: String(d?.note ?? ""),
          }))
          .filter((d) => d.name)
      : [];
    const payload: DiligencePayload = {
      score: Number(scored.data.score ?? 0),
      dimensions,
      rationale: String(scored.data.rationale ?? ""),
      questions: Array.isArray(scored.data.questions)
        ? scored.data.questions.filter((x) => x?.question)
        : [],
      sources: research.sources.map((s) => s.uri),
      signalsUsed: signalHeadlines.map(
        (s) => `${s.date ? `[${s.date}] ` : ""}${s.category ? `(${s.category}) ` : ""}${s.signal}`,
      ),
    };
    return savePlatformContent({
      type: "diligence",
      subject: company,
      title: `Diligence — ${company}`,
      payload,
      sources: payload.sources,
      generatedBy,
    });
  });
}

// ══════════════════════════════════════════════════════════════
// Investment theses + thesis screening (DealDesk port, Sheets-backed).
// Theses are the registry; screening is an ON-DEMAND Gemini run (no
// heartbeats/agents) whose candidates come from stored signals + one
// grounded web search; matches persist to "Thesis Matches".
// ══════════════════════════════════════════════════════════════

export const THESES_HEADERS = [
  "ID",
  "Name",
  "Sectors",
  "Stages",
  "Geos",
  "Keywords",
  "Exclusions",
  "Narrative",
  "Status",
  "Created By",
  "Created At",
  "Updated At",
  "Last Screened At",
];

export const THESIS_MATCHES_HEADERS = [
  "ID",
  "Thesis ID",
  "Company",
  "Website",
  "Description",
  "Sector",
  "Stage",
  "Geo",
  "Fit Score",
  "Fit Rationale",
  "Source URL",
  "Origin",
  "Status",
  "Screened At",
  "Screened By",
];

export async function buildTheses(): Promise<Thesis[]> {
  const rows = await readTab(TAB_NAMES.theses);
  if (rows.length < 2) return [];
  const h = headerIndex(rows);
  return rows
    .slice(1)
    .filter((row) => cell(row, h["id"]) && cell(row, h["name"]))
    .map((row) => {
      const status = cell(row, h["status"]);
      return {
        id: cell(row, h["id"]),
        name: cell(row, h["name"]),
        sectors: splitList(cell(row, h["sectors"])),
        stages: splitList(cell(row, h["stages"])),
        geos: splitList(cell(row, h["geos"])),
        keywords: splitList(cell(row, h["keywords"])),
        exclusions: cell(row, h["exclusions"]),
        narrative: cell(row, h["narrative"]),
        status: isThesisStatus(status) ? status : "active",
        createdBy: cell(row, h["created by"]),
        createdAt: cell(row, h["created at"]),
        updatedAt: cell(row, h["updated at"]),
        lastScreenedAt: cell(row, h["last screened at"]),
      };
    })
    .sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));
}

export async function addThesis(input: NewThesis, createdBy: string): Promise<Thesis> {
  const now = new Date().toISOString();
  const thesis: Thesis = {
    id: crypto.randomUUID(),
    name: input.name.trim(),
    sectors: input.sectors.map((s) => s.trim()).filter(Boolean),
    stages: input.stages.map((s) => s.trim()).filter(Boolean),
    geos: input.geos.map((s) => s.trim()).filter(Boolean),
    keywords: input.keywords.map((s) => s.trim()).filter(Boolean),
    exclusions: input.exclusions.trim(),
    narrative: input.narrative.trim(),
    status: "active",
    createdBy,
    createdAt: now,
    updatedAt: now,
    lastScreenedAt: "",
  };
  if (!thesis.name) throw new Error("Thesis name is required");
  if (thesis.sectors.length === 0) throw new Error("At least one sector is required");
  await ensureTab(TAB_NAMES.theses, THESES_HEADERS);
  await appendSheetRow(TAB_NAMES.theses, [
    thesis.id,
    thesis.name,
    joinList(thesis.sectors),
    joinList(thesis.stages),
    joinList(thesis.geos),
    joinList(thesis.keywords),
    thesis.exclusions,
    thesis.narrative,
    thesis.status,
    thesis.createdBy,
    thesis.createdAt,
    thesis.updatedAt,
    thesis.lastScreenedAt,
  ]);
  await logOpsEvent({
    action: "edit",
    source: "platform-thesis",
    status: "ok",
    summary: `Created thesis "${thesis.name}"`,
    records: 1,
  });
  return thesis;
}

// Locate a row by ID and update named columns in one batched cell write.
// Returns false when the ID isn't present (tab missing or row deleted).
async function updateRowCells(
  tabName: string,
  id: string,
  values: Record<string, string>,
): Promise<boolean> {
  const rows = await readTab(tabName);
  if (rows.length < 2) return false;
  const h = headerIndex(rows);
  const idx = rows.slice(1).findIndex((row) => cell(row, h["id"]) === id);
  if (idx === -1) return false;
  const rowNumber = idx + 2; // 1-based, after the header row
  const updates: { range: string; value: string }[] = [];
  for (const [header, value] of Object.entries(values)) {
    const col = h[header];
    if (col == null) continue;
    updates.push({ range: `${colLetters(col)}${rowNumber}`, value });
  }
  await updateSheetCells(tabName, updates);
  return true;
}

export async function updateThesis(id: string, input: NewThesis): Promise<boolean> {
  const ok = await updateRowCells(TAB_NAMES.theses, id, {
    name: input.name.trim(),
    sectors: joinList(input.sectors),
    stages: joinList(input.stages),
    geos: joinList(input.geos),
    keywords: joinList(input.keywords),
    exclusions: input.exclusions.trim(),
    narrative: input.narrative.trim(),
    "updated at": new Date().toISOString(),
  });
  if (ok) {
    await logOpsEvent({
      action: "edit",
      source: "platform-thesis",
      status: "ok",
      summary: `Updated thesis "${input.name.trim()}"`,
      records: 1,
    });
  }
  return ok;
}

export async function setThesisStatus(id: string, status: ThesisStatus): Promise<boolean> {
  const ok = await updateRowCells(TAB_NAMES.theses, id, {
    status,
    "updated at": new Date().toISOString(),
  });
  if (ok) {
    await logOpsEvent({
      action: "edit",
      source: "platform-thesis",
      status: "ok",
      summary: `Thesis status → ${status}`,
      records: 1,
    });
  }
  return ok;
}

export async function buildThesisMatches(): Promise<ThesisMatch[]> {
  const rows = await readTab(TAB_NAMES.thesisMatches);
  if (rows.length < 2) return [];
  const h = headerIndex(rows);
  return rows
    .slice(1)
    .filter((row) => cell(row, h["id"]) && cell(row, h["company"]))
    .map((row) => {
      const status = cell(row, h["status"]);
      const origin = cell(row, h["origin"]);
      return {
        id: cell(row, h["id"]),
        thesisId: cell(row, h["thesis id"]),
        company: cell(row, h["company"]),
        website: cell(row, h["website"]),
        description: cell(row, h["description"]),
        sector: cell(row, h["sector"]),
        stage: cell(row, h["stage"]),
        geo: cell(row, h["geo"]),
        fitScore: Number(cell(row, h["fit score"])) || 0,
        fitRationale: cell(row, h["fit rationale"]),
        sourceUrl: cell(row, h["source url"]),
        origin: origin === "web" ? ("web" as const) : ("signals" as const),
        status: isMatchStatus(status) ? status : "sourced",
        screenedAt: cell(row, h["screened at"]),
        screenedBy: cell(row, h["screened by"]),
      };
    })
    .sort((a, b) => b.fitScore - a.fitScore || (a.screenedAt < b.screenedAt ? 1 : -1));
}

export async function setThesisMatchStatus(
  id: string,
  status: ThesisMatchStatus,
): Promise<boolean> {
  return updateRowCells(TAB_NAMES.thesisMatches, id, { status });
}

// ── Screening ────────────────────────────────────────────────────

// Candidate companies from the stored Signals tab: hook-matched rows first,
// then the most recent others (the Gem drops non-fits, so over-supplying is
// fine — the cap just bounds tokens). Portfolio companies never qualify.
interface SignalCandidate {
  company: string;
  lines: string[];
  urls: string[];
}

async function readSignalCandidates(
  hooks: string[],
  portcoNames: Set<string>,
  maxCompanies = 20,
): Promise<SignalCandidate[]> {
  const rows = await readTab(TAB_NAMES.signals);
  if (rows.length < 2) return [];
  const h = headerIndex(rows);
  const lowerHooks = hooks.map((k) => k.toLowerCase()).filter((k) => k.length > 2);
  interface Entry {
    candidate: SignalCandidate;
    hooked: boolean;
    latest: string;
  }
  const byCompany = new Map<string, Entry>();
  for (const row of rows.slice(1)) {
    const company = cell(row, h["company"]);
    const signal = cell(row, h["signal"]);
    if (!company || !signal) continue;
    const key = company.toLowerCase();
    if (portcoNames.has(key)) continue;
    const date = cell(row, h["date found"]);
    const url = cell(row, h["source url"]);
    const hay = `${company} ${signal} ${cell(row, h["category"])}`.toLowerCase();
    const hooked = lowerHooks.some((k) => hay.includes(k));
    let entry = byCompany.get(key);
    if (!entry) {
      entry = { candidate: { company, lines: [], urls: [] }, hooked: false, latest: "" };
      byCompany.set(key, entry);
    }
    if (entry.candidate.lines.length < 3) {
      entry.candidate.lines.push(`${date ? `[${date}] ` : ""}${signal}`);
      if (/^https?:\/\//i.test(url)) entry.candidate.urls.push(url);
    }
    entry.hooked = entry.hooked || hooked;
    if (date > entry.latest) entry.latest = date;
  }
  return [...byCompany.values()]
    .sort((a, b) => Number(b.hooked) - Number(a.hooked) || (a.latest < b.latest ? 1 : -1))
    .slice(0, maxCompanies)
    .map((e) => e.candidate);
}

export interface ScreenThesisResult {
  added: ThesisMatch[];
  duplicates: number;
}

interface RawScreenMatch {
  company?: string;
  website?: string;
  stage?: string;
  sector?: string;
  geo?: string;
  description?: string;
  fitScore?: number;
  fitRationale?: string;
  sourceUrl?: string;
  origin?: string;
}

export async function screenThesis(
  thesisId: string,
  screenedBy: string,
): Promise<ScreenThesisResult> {
  const theses = await buildTheses();
  const thesis = theses.find((t) => t.id === thesisId);
  if (!thesis) throw new Error("Thesis not found");

  return audited("platform-thesis", `Screened thesis "${thesis.name}"`, async () => {
    const criteria = thesisCriteriaText(thesis);
    const portcos = await buildPortfolioCompanies().catch(() => []);
    const portcoNames = new Set(portcos.map((p) => p.name.trim().toLowerCase()));

    const [candidates, web] = await Promise.all([
      readSignalCandidates([...thesis.sectors, ...thesis.keywords], portcoNames),
      groundedSearch(
        `Find venture-backed startups matching this investment thesis:\n${criteria}\n` +
          `Prefer companies with a funding round announced in the last 18 months. For each company give: ` +
          `name, website, what it builds, latest funding stage and round size, headquarters location. ` +
          `Only include companies whose funding stage you can verify.`,
        1400,
      ).catch(() => ({ text: "", sources: [] }) as { text: string; sources: { uri: string; title: string }[] }),
    ]);

    const signalsBlock = candidates
      .map((c) => `## ${c.company}\n${c.lines.join("\n")}${c.urls.length ? `\nurls: ${c.urls.join(" ")}` : ""}`)
      .join("\n");

    const res = await runGemJSON<{ matches?: RawScreenMatch[] }>(
      thesisScreenGem,
      `Screen the candidates against this investment thesis:\n${criteria}`,
      [
        { label: "CANDIDATES FROM STORED SIGNALS", content: signalsBlock },
        {
          label: "WEB RESEARCH (grounded)",
          content: web.text ? `${web.text}\n\nSources:\n${numberedSources(web.sources)}` : "",
        },
        {
          label: "PORTFOLIO (never return these)",
          content: portcos.map((p) => `- ${p.name}`).join("\n"),
        },
      ],
    );
    if (!res.ok || !res.data) throw new Error(res.error || "Thesis screen failed");

    // Belt & braces mirroring DealDesk's save gate: score floor, no portcos,
    // and only URLs we actually supplied (grounded web + stored-signal URLs).
    const allowedUrls = new Set([
      ...web.sources.map((s) => s.uri),
      ...candidates.flatMap((c) => c.urls),
    ]);
    const existing = await buildThesisMatches();
    const existingKeys = new Set(existing.map((m) => matchKeyOf(m)));
    const now = new Date().toISOString();
    const seen = new Set<string>();
    let duplicates = 0;
    const added: ThesisMatch[] = [];
    for (const raw of res.data.matches ?? []) {
      const company = (raw.company ?? "").trim();
      const score = Math.round(Number(raw.fitScore) || 0);
      if (!company || portcoNames.has(company.toLowerCase())) continue;
      if (score < MIN_FIT_SCORE) continue;
      const key = matchKeyOf({ thesisId, company });
      if (existingKeys.has(key) || seen.has(key)) {
        duplicates++;
        continue;
      }
      seen.add(key);
      const sourceUrl = (raw.sourceUrl ?? "").trim();
      added.push({
        id: crypto.randomUUID(),
        thesisId,
        company,
        website: (raw.website ?? "").trim(),
        description: (raw.description ?? "").trim(),
        sector: (raw.sector ?? "").trim(),
        stage: (raw.stage ?? "").trim(),
        geo: (raw.geo ?? "").trim(),
        fitScore: Math.min(100, score),
        fitRationale: (raw.fitRationale ?? "").trim(),
        sourceUrl: allowedUrls.has(sourceUrl) ? sourceUrl : "",
        origin: raw.origin === "web" ? "web" : "signals",
        status: "sourced",
        screenedAt: now,
        screenedBy,
      });
    }

    if (added.length > 0) {
      await ensureTab(TAB_NAMES.thesisMatches, THESIS_MATCHES_HEADERS);
      await appendSheetRows(
        TAB_NAMES.thesisMatches,
        added.map((m) => [
          m.id,
          m.thesisId,
          m.company,
          m.website,
          m.description,
          m.sector,
          m.stage,
          m.geo,
          String(m.fitScore),
          m.fitRationale,
          m.sourceUrl,
          m.origin,
          m.status,
          m.screenedAt,
          m.screenedBy,
        ]),
      );
    }
    await updateRowCells(TAB_NAMES.theses, thesisId, { "last screened at": now });
    return { added, duplicates };
  });
}

// ── Promote a match to the Targeting pipeline ────────────────────
// Resolves the company domain, finds C-suite / founders via Apollo, and
// appends those people to Targets (not a fake company-as-person row). The
// Companies page is a derived directory — people with company=X seed X there.

export interface PromoteMatchResult {
  ok: boolean;
  company: string;
  peopleAdded: number;
  duplicates: number;
  domain?: string;
  /** Company name couldn't be resolved to a domain for Apollo. */
  unresolvedDomain?: boolean;
  /** Soft failure (Apollo access, empty search) — match may still be promoted. */
  warning?: string;
}

function promoteIdentityKeys(
  name: string,
  company: string,
  email: string,
  linkedinUrl: string,
): string[] {
  const keys: string[] = [];
  for (const e of (email || "").split(";")) {
    const k = e.trim().toLowerCase();
    if (k) keys.push(k);
  }
  const li = (linkedinUrl || "").trim().toLowerCase().replace(/\/+$/, "");
  if (li) keys.push(`li:${li}`);
  const nc = `${(name || "").trim()}|${(company || "").trim()}`.toLowerCase();
  if (nc.length > 1) keys.push(`nc:${nc}`);
  return keys;
}

function normalizePromoteDomain(raw: string | undefined | null): string {
  return (raw || "").trim().toLowerCase().replace(/^www\./, "");
}

/**
 * Thesis-screen websites are often wrong (e.g. architectlabs.ai vs .com).
 * Prefer Sumble's canonical domain, then fall back to the match website, and
 * keep both as candidates so Apollo can retry.
 */
async function resolvePromoteDomains(
  company: string,
  website: string,
): Promise<string[]> {
  const ordered: string[] = [];
  const push = (d: string) => {
    const n = normalizePromoteDomain(d);
    if (n && !ordered.includes(n)) ordered.push(n);
  };

  if (isSumbleConfigured()) {
    try {
      const m = await matchOrganization(company, website || undefined);
      if (m.org?.domain) push(m.org.domain);
    } catch (e) {
      console.error("[promote] matchOrganization failed", company, e);
    }
  }

  const fromWebsite = extractDomain(website);
  if (fromWebsite) push(fromWebsite);

  return ordered;
}

type ApolloPersonHit = {
  id: string;
  firstName: string;
  title: string;
  company: string;
};

async function searchPromotePeople(
  domains: string[],
): Promise<{ people: ApolloPersonHit[]; domain: string; accessDenied?: string }> {
  let accessDenied: string | undefined;

  for (const domain of domains) {
    // 1) Titles + seniority (strict)
    const strict = await searchPeople({
      titles: PROMOTE_TITLES,
      seniorities: PROMOTE_SENIORITIES,
      organizationDomains: [domain],
      perPage: PROMOTE_PER_COMPANY,
    });
    if (strict.accessDenied) {
      accessDenied =
        strict.error ||
        "Apollo people-search isn't accessible with this API key/plan.";
      continue;
    }
    if (strict.people.length > 0) {
      const leaders = strict.people.filter((p) => LEADERSHIP_TITLE_RE.test(p.title || ""));
      const picked = (leaders.length > 0 ? leaders : strict.people).slice(0, PROMOTE_PER_COMPANY);
      return { people: picked, domain };
    }

    // 2) Seniority-only — catches Co-Founder / CSO when title facets miss
    const broad = await searchPeople({
      seniorities: PROMOTE_SENIORITIES,
      organizationDomains: [domain],
      perPage: PROMOTE_PER_COMPANY,
    });
    if (broad.accessDenied) {
      accessDenied =
        broad.error ||
        "Apollo people-search isn't accessible with this API key/plan.";
      continue;
    }
    const leaders = broad.people.filter((p) => LEADERSHIP_TITLE_RE.test(p.title || ""));
    if (leaders.length > 0) {
      return { people: leaders.slice(0, PROMOTE_PER_COMPANY), domain };
    }
  }

  return { people: [], domain: domains[0] || "", accessDenied };
}

export async function promoteThesisMatch(
  matchId: string,
  promotedBy: string,
): Promise<PromoteMatchResult> {
  const [matches, theses] = await Promise.all([buildThesisMatches(), buildTheses()]);
  const match = matches.find((m) => m.id === matchId);
  if (!match) throw new Error("Thesis match not found");
  const thesis = theses.find((t) => t.id === match.thesisId);
  const thesisName = thesis?.name || "thesis";
  const sector = match.sector || thesis?.sectors[0] || "";
  const reasonSurfaced =
    `Thesis fit ${match.fitScore}/100 — ${match.fitRationale}`.slice(0, 300);
  const source = `Thesis — ${thesisName}`;

  const domains = await resolvePromoteDomains(match.company, match.website || "");
  if (domains.length === 0) {
    await setThesisMatchStatus(matchId, "promoted");
    await logOpsEvent({
      action: "edit",
      source: "platform-thesis",
      status: "error",
      summary: `Promoted "${match.company}" but couldn't resolve a domain for people search (${thesisName})`,
      records: 0,
      details: { fitScore: match.fitScore, promotedBy, website: match.website || "" },
    });
    return {
      ok: true,
      company: match.company,
      peopleAdded: 0,
      duplicates: 0,
      unresolvedDomain: true,
      warning:
        "Couldn't resolve a company domain — marked promoted, but no people were added. Add a website on the match or find leaders via Network Search.",
    };
  }

  let peopleAdded = 0;
  let duplicates = 0;
  let warning: string | undefined;
  let domain = domains[0];

  try {
    const search = await searchPromotePeople(domains);
    domain = search.domain || domain;
    if (search.accessDenied && search.people.length === 0) {
      warning = search.accessDenied;
    } else if (search.people.length === 0) {
      warning = `No C-suite or founders found at ${match.company} (tried ${domains.join(", ")}).`;
    } else {
      const existing = await buildTargets().catch(() => []);
      const known = new Set<string>();
      for (const t of existing) {
        for (const k of promoteIdentityKeys(t.name, t.company, t.email, t.linkedinUrl || "")) {
          known.add(k);
        }
      }
      const seen = new Set<string>();
      const rows: TargetRowInput[] = [];

      for (const p of search.people) {
        if (!p.id) continue;
        let email = "";
        let phone = "";
        let name = p.firstName || "";
        let title = p.title || "";
        let location = match.geo || "";
        let linkedinUrl = "";
        // Always stamp the thesis company name so Companies indexes cleanly.
        const company = match.company;

        try {
          const r = await enrichPerson({
            id: p.id,
            organizationName: company,
          });
          if (r.accessDenied) {
            warning =
              r.error ||
              "Apollo enrichment isn't accessible with this API key/plan.";
            break;
          }
          if (r.found) {
            email = r.email || "";
            phone = r.phoneSource === "company" ? "" : r.phone || "";
            name = r.name || name;
            title = r.title || title;
            linkedinUrl = r.linkedinUrl || "";
            const city = [r.city, r.state].filter(Boolean).join(", ");
            if (city) location = city;
          }
        } catch (e) {
          console.error("[promote] enrich failed", p.firstName, e);
          const msg = e instanceof Error ? e.message : "";
          if (/APOLLO_API_KEY/.test(msg)) throw e;
        }

        const keys = promoteIdentityKeys(name, company, email, linkedinUrl);
        if (keys.length === 0) continue;
        if (keys.some((k) => known.has(k) || seen.has(k))) {
          duplicates++;
          continue;
        }
        keys.forEach((k) => seen.add(k));

        const parts = name.trim().split(/\s+/);
        rows.push({
          firstName: parts[0] || p.firstName || "",
          lastName: parts.slice(1).join(" "),
          company,
          role: title || "Executive",
          linkedin: linkedinUrl,
          email,
          phone,
          location,
          sector,
          stage: "Prospecting",
          source,
          researchPurpose: thesisName,
          reasonSurfaced,
        });
      }

      if (rows.length > 0) {
        await appendTargetRows(rows);
        peopleAdded = rows.length;
      } else if (!warning && duplicates > 0) {
        warning = `Leaders at ${match.company} are already in Targets.`;
      }
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : "People search failed";
    if (/APOLLO_API_KEY/.test(msg)) throw new Error("APOLLO_API_KEY is not configured.");
    throw e;
  }

  await setThesisMatchStatus(matchId, "promoted");
  await logOpsEvent({
    action: "edit",
    source: "platform-thesis",
    status: peopleAdded > 0 ? "ok" : warning ? "error" : "ok",
    summary:
      peopleAdded > 0
        ? `Promoted "${match.company}" — added ${peopleAdded} leader(s) to Targets (${thesisName})`
        : `Promoted "${match.company}" — no new people added (${thesisName})`,
    records: peopleAdded,
    details: {
      fitScore: match.fitScore,
      promotedBy,
      domain,
      domainsTried: domains.join(", "),
      website: match.website || "",
      duplicates,
      warning: warning || "",
    },
  });

  return {
    ok: true,
    company: match.company,
    peopleAdded,
    duplicates,
    domain,
    warning,
  };
}
