/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TargetingRouteImport } from './routes/targeting'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as QueryRouteImport } from './routes/query'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'

const TargetingRoute = TargetingRouteImport.update({
  id: '/targeting',
  path: '/targeting',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/portfolio': typeof PortfolioRoute
  '/query': typeof QueryRoute
  '/signals': typeof SignalsRoute
  '/targeting': typeof TargetingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/portfolio': typeof PortfolioRoute
  '/query': typeof QueryRoute
  '/signals': typeof SignalsRoute
  '/targeting': typeof TargetingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/portfolio': typeof PortfolioRoute
  '/query': typeof QueryRoute
  '/signals': typeof SignalsRoute
  '/targeting': typeof TargetingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/crm'
    | '/dashboard'
    | '/events'
    | '/portfolio'
    | '/query'
    | '/signals'
    | '/targeting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/crm'
    | '/dashboard'
    | '/events'
    | '/portfolio'
    | '/query'
    | '/signals'
    | '/targeting'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/crm'
    | '/dashboard'
    | '/events'
    | '/portfolio'
    | '/query'
    | '/signals'
    | '/targeting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  PortfolioRoute: typeof PortfolioRoute
  QueryRoute: typeof QueryRoute
  SignalsRoute: typeof SignalsRoute
  TargetingRoute: typeof TargetingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/targeting': {
      id: '/targeting'
      path: '/targeting'
      fullPath: '/targeting'
      preLoaderRoute: typeof TargetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  PortfolioRoute: PortfolioRoute,
  QueryRoute: QueryRoute,
  SignalsRoute: SignalsRoute,
  TargetingRoute: TargetingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
